# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import records_pb2 as slate_dot_v1_dot_records__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in slate/v1/records_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecordsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Begin = channel.unary_unary(
                '/slate.v1.Records/Begin',
                request_serializer=slate_dot_v1_dot_records__pb2.BeginRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.BeginResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/slate.v1.Records/Commit',
                request_serializer=slate_dot_v1_dot_records__pb2.CommitRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.Rollback = channel.unary_unary(
                '/slate.v1.Records/Rollback',
                request_serializer=slate_dot_v1_dot_records__pb2.RollbackRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.RollbackResponse.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/slate.v1.Records/Insert',
                request_serializer=slate_dot_v1_dot_records__pb2.InsertRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/slate.v1.Records/Update',
                request_serializer=slate_dot_v1_dot_records__pb2.UpdateRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/slate.v1.Records/Delete',
                request_serializer=slate_dot_v1_dot_records__pb2.DeleteRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.DeleteWhere = channel.unary_unary(
                '/slate.v1.Records/DeleteWhere',
                request_serializer=slate_dot_v1_dot_records__pb2.DeleteWhereRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.UpdateWhere = channel.unary_unary(
                '/slate.v1.Records/UpdateWhere',
                request_serializer=slate_dot_v1_dot_records__pb2.UpdateWhereRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Batch = channel.unary_unary(
                '/slate.v1.Records/Batch',
                request_serializer=slate_dot_v1_dot_records__pb2.BatchRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/slate.v1.Records/Get',
                request_serializer=slate_dot_v1_dot_records__pb2.GetRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_stream(
                '/slate.v1.Records/Query',
                request_serializer=slate_dot_v1_dot_records__pb2.QueryRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Join = channel.unary_stream(
                '/slate.v1.Records/Join',
                request_serializer=slate_dot_v1_dot_records__pb2.JoinRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.Aggregate = channel.unary_stream(
                '/slate.v1.Records/Aggregate',
                request_serializer=slate_dot_v1_dot_records__pb2.AggregateRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.AggregateResponse.FromString,
                _registered_method=True)
        self.Related = channel.unary_unary(
                '/slate.v1.Records/Related',
                request_serializer=slate_dot_v1_dot_records__pb2.RelatedRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.RelatedResponse.FromString,
                _registered_method=True)
        self.Explain = channel.unary_unary(
                '/slate.v1.Records/Explain',
                request_serializer=slate_dot_v1_dot_records__pb2.ExplainRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.ExplainResponse.FromString,
                _registered_method=True)
        self.ExplainJoin = channel.unary_unary(
                '/slate.v1.Records/ExplainJoin',
                request_serializer=slate_dot_v1_dot_records__pb2.ExplainJoinRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.JoinExplainResponse.FromString,
                _registered_method=True)
        self.ExplainAggregate = channel.unary_unary(
                '/slate.v1.Records/ExplainAggregate',
                request_serializer=slate_dot_v1_dot_records__pb2.ExplainAggregateRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.AggregateExplainResponse.FromString,
                _registered_method=True)
        self.Leadership = channel.unary_unary(
                '/slate.v1.Records/Leadership',
                request_serializer=slate_dot_v1_dot_records__pb2.LeadershipRequest.SerializeToString,
                response_deserializer=slate_dot_v1_dot_records__pb2.LeadershipStatus.FromString,
                _registered_method=True)


class RecordsServicer:
    """Missing associated documentation comment in .proto file."""

    def Begin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWhere(self, request, context):
        """Predicate writes: one statement rather than a query, a round trip and a
        write per row. Both go to the writer, like every other write.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWhere(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Batch(self, request, context):
        """Several writes in one round trip. The caller says whether they are
        independent or atomic; there is no default.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Aggregate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Related(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Explain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainJoin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainAggregate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Leadership(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecordsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Begin': grpc.unary_unary_rpc_method_handler(
                    servicer.Begin,
                    request_deserializer=slate_dot_v1_dot_records__pb2.BeginRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.BeginResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=slate_dot_v1_dot_records__pb2.CommitRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.CommitResponse.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=slate_dot_v1_dot_records__pb2.RollbackRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.RollbackResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=slate_dot_v1_dot_records__pb2.InsertRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.WriteResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=slate_dot_v1_dot_records__pb2.UpdateRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.WriteResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=slate_dot_v1_dot_records__pb2.DeleteRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.WriteResponse.SerializeToString,
            ),
            'DeleteWhere': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWhere,
                    request_deserializer=slate_dot_v1_dot_records__pb2.DeleteWhereRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.WriteResponse.SerializeToString,
            ),
            'UpdateWhere': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWhere,
                    request_deserializer=slate_dot_v1_dot_records__pb2.UpdateWhereRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.WriteResponse.SerializeToString,
            ),
            'Batch': grpc.unary_unary_rpc_method_handler(
                    servicer.Batch,
                    request_deserializer=slate_dot_v1_dot_records__pb2.BatchRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.BatchResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=slate_dot_v1_dot_records__pb2.GetRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.GetResponse.SerializeToString,
            ),
            'Query': grpc.unary_stream_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=slate_dot_v1_dot_records__pb2.QueryRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.QueryResponse.SerializeToString,
            ),
            'Join': grpc.unary_stream_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=slate_dot_v1_dot_records__pb2.JoinRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.JoinResponse.SerializeToString,
            ),
            'Aggregate': grpc.unary_stream_rpc_method_handler(
                    servicer.Aggregate,
                    request_deserializer=slate_dot_v1_dot_records__pb2.AggregateRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.AggregateResponse.SerializeToString,
            ),
            'Related': grpc.unary_unary_rpc_method_handler(
                    servicer.Related,
                    request_deserializer=slate_dot_v1_dot_records__pb2.RelatedRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.RelatedResponse.SerializeToString,
            ),
            'Explain': grpc.unary_unary_rpc_method_handler(
                    servicer.Explain,
                    request_deserializer=slate_dot_v1_dot_records__pb2.ExplainRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.ExplainResponse.SerializeToString,
            ),
            'ExplainJoin': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainJoin,
                    request_deserializer=slate_dot_v1_dot_records__pb2.ExplainJoinRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.JoinExplainResponse.SerializeToString,
            ),
            'ExplainAggregate': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainAggregate,
                    request_deserializer=slate_dot_v1_dot_records__pb2.ExplainAggregateRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.AggregateExplainResponse.SerializeToString,
            ),
            'Leadership': grpc.unary_unary_rpc_method_handler(
                    servicer.Leadership,
                    request_deserializer=slate_dot_v1_dot_records__pb2.LeadershipRequest.FromString,
                    response_serializer=slate_dot_v1_dot_records__pb2.LeadershipStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'slate.v1.Records', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('slate.v1.Records', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Records:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Begin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/Begin',
            slate_dot_v1_dot_records__pb2.BeginRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.BeginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/Commit',
            slate_dot_v1_dot_records__pb2.CommitRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/Rollback',
            slate_dot_v1_dot_records__pb2.RollbackRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/Insert',
            slate_dot_v1_dot_records__pb2.InsertRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/Update',
            slate_dot_v1_dot_records__pb2.UpdateRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/Delete',
            slate_dot_v1_dot_records__pb2.DeleteRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWhere(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/DeleteWhere',
            slate_dot_v1_dot_records__pb2.DeleteWhereRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWhere(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/UpdateWhere',
            slate_dot_v1_dot_records__pb2.UpdateWhereRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Batch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/Batch',
            slate_dot_v1_dot_records__pb2.BatchRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/Get',
            slate_dot_v1_dot_records__pb2.GetRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/slate.v1.Records/Query',
            slate_dot_v1_dot_records__pb2.QueryRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/slate.v1.Records/Join',
            slate_dot_v1_dot_records__pb2.JoinRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Aggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/slate.v1.Records/Aggregate',
            slate_dot_v1_dot_records__pb2.AggregateRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.AggregateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Related(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/Related',
            slate_dot_v1_dot_records__pb2.RelatedRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.RelatedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Explain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/Explain',
            slate_dot_v1_dot_records__pb2.ExplainRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.ExplainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainJoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/ExplainJoin',
            slate_dot_v1_dot_records__pb2.ExplainJoinRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.JoinExplainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainAggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/ExplainAggregate',
            slate_dot_v1_dot_records__pb2.ExplainAggregateRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.AggregateExplainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Leadership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.v1.Records/Leadership',
            slate_dot_v1_dot_records__pb2.LeadershipRequest.SerializeToString,
            slate_dot_v1_dot_records__pb2.LeadershipStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
