"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from . import records_pb2 as _records_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class RecordsStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RecordsAsyncStub: ...
    Begin: _grpc.UnaryUnaryMultiCallable[_records_pb2.BeginRequest, _records_pb2.BeginResponse]
    Commit: _grpc.UnaryUnaryMultiCallable[_records_pb2.CommitRequest, _records_pb2.CommitResponse]
    Rollback: _grpc.UnaryUnaryMultiCallable[_records_pb2.RollbackRequest, _records_pb2.RollbackResponse]
    Insert: _grpc.UnaryUnaryMultiCallable[_records_pb2.InsertRequest, _records_pb2.WriteResponse]
    Update: _grpc.UnaryUnaryMultiCallable[_records_pb2.UpdateRequest, _records_pb2.WriteResponse]
    Delete: _grpc.UnaryUnaryMultiCallable[_records_pb2.DeleteRequest, _records_pb2.WriteResponse]
    DeleteWhere: _grpc.UnaryUnaryMultiCallable[_records_pb2.DeleteWhereRequest, _records_pb2.WriteResponse]
    """Predicate writes: one statement rather than a query, a round trip and a
    write per row. Both go to the writer, like every other write.
    """
    UpdateWhere: _grpc.UnaryUnaryMultiCallable[_records_pb2.UpdateWhereRequest, _records_pb2.WriteResponse]
    Batch: _grpc.UnaryUnaryMultiCallable[_records_pb2.BatchRequest, _records_pb2.BatchResponse]
    """Several writes in one round trip. The caller says whether they are
    independent or atomic; there is no default.
    """
    Get: _grpc.UnaryUnaryMultiCallable[_records_pb2.GetRequest, _records_pb2.GetResponse]
    Query: _grpc.UnaryStreamMultiCallable[_records_pb2.QueryRequest, _records_pb2.QueryResponse]
    Join: _grpc.UnaryStreamMultiCallable[_records_pb2.JoinRequest, _records_pb2.JoinResponse]
    Aggregate: _grpc.UnaryStreamMultiCallable[_records_pb2.AggregateRequest, _records_pb2.AggregateResponse]
    Related: _grpc.UnaryUnaryMultiCallable[_records_pb2.RelatedRequest, _records_pb2.RelatedResponse]
    Explain: _grpc.UnaryUnaryMultiCallable[_records_pb2.ExplainRequest, _records_pb2.ExplainResponse]
    ExplainJoin: _grpc.UnaryUnaryMultiCallable[_records_pb2.ExplainJoinRequest, _records_pb2.JoinExplainResponse]
    ExplainAggregate: _grpc.UnaryUnaryMultiCallable[_records_pb2.ExplainAggregateRequest, _records_pb2.AggregateExplainResponse]
    Leadership: _grpc.UnaryUnaryMultiCallable[_records_pb2.LeadershipRequest, _records_pb2.LeadershipStatus]

@_typing.type_check_only
class RecordsAsyncStub(RecordsStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Begin: _aio.UnaryUnaryMultiCallable[_records_pb2.BeginRequest, _records_pb2.BeginResponse]  # type: ignore[assignment]
    Commit: _aio.UnaryUnaryMultiCallable[_records_pb2.CommitRequest, _records_pb2.CommitResponse]  # type: ignore[assignment]
    Rollback: _aio.UnaryUnaryMultiCallable[_records_pb2.RollbackRequest, _records_pb2.RollbackResponse]  # type: ignore[assignment]
    Insert: _aio.UnaryUnaryMultiCallable[_records_pb2.InsertRequest, _records_pb2.WriteResponse]  # type: ignore[assignment]
    Update: _aio.UnaryUnaryMultiCallable[_records_pb2.UpdateRequest, _records_pb2.WriteResponse]  # type: ignore[assignment]
    Delete: _aio.UnaryUnaryMultiCallable[_records_pb2.DeleteRequest, _records_pb2.WriteResponse]  # type: ignore[assignment]
    DeleteWhere: _aio.UnaryUnaryMultiCallable[_records_pb2.DeleteWhereRequest, _records_pb2.WriteResponse]  # type: ignore[assignment]
    """Predicate writes: one statement rather than a query, a round trip and a
    write per row. Both go to the writer, like every other write.
    """
    UpdateWhere: _aio.UnaryUnaryMultiCallable[_records_pb2.UpdateWhereRequest, _records_pb2.WriteResponse]  # type: ignore[assignment]
    Batch: _aio.UnaryUnaryMultiCallable[_records_pb2.BatchRequest, _records_pb2.BatchResponse]  # type: ignore[assignment]
    """Several writes in one round trip. The caller says whether they are
    independent or atomic; there is no default.
    """
    Get: _aio.UnaryUnaryMultiCallable[_records_pb2.GetRequest, _records_pb2.GetResponse]  # type: ignore[assignment]
    Query: _aio.UnaryStreamMultiCallable[_records_pb2.QueryRequest, _records_pb2.QueryResponse]  # type: ignore[assignment]
    Join: _aio.UnaryStreamMultiCallable[_records_pb2.JoinRequest, _records_pb2.JoinResponse]  # type: ignore[assignment]
    Aggregate: _aio.UnaryStreamMultiCallable[_records_pb2.AggregateRequest, _records_pb2.AggregateResponse]  # type: ignore[assignment]
    Related: _aio.UnaryUnaryMultiCallable[_records_pb2.RelatedRequest, _records_pb2.RelatedResponse]  # type: ignore[assignment]
    Explain: _aio.UnaryUnaryMultiCallable[_records_pb2.ExplainRequest, _records_pb2.ExplainResponse]  # type: ignore[assignment]
    ExplainJoin: _aio.UnaryUnaryMultiCallable[_records_pb2.ExplainJoinRequest, _records_pb2.JoinExplainResponse]  # type: ignore[assignment]
    ExplainAggregate: _aio.UnaryUnaryMultiCallable[_records_pb2.ExplainAggregateRequest, _records_pb2.AggregateExplainResponse]  # type: ignore[assignment]
    Leadership: _aio.UnaryUnaryMultiCallable[_records_pb2.LeadershipRequest, _records_pb2.LeadershipStatus]  # type: ignore[assignment]

class RecordsServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Begin(
        self,
        request: _records_pb2.BeginRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.BeginResponse, _abc.Awaitable[_records_pb2.BeginResponse]]: ...

    @_abc_1.abstractmethod
    def Commit(
        self,
        request: _records_pb2.CommitRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.CommitResponse, _abc.Awaitable[_records_pb2.CommitResponse]]: ...

    @_abc_1.abstractmethod
    def Rollback(
        self,
        request: _records_pb2.RollbackRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.RollbackResponse, _abc.Awaitable[_records_pb2.RollbackResponse]]: ...

    @_abc_1.abstractmethod
    def Insert(
        self,
        request: _records_pb2.InsertRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.WriteResponse, _abc.Awaitable[_records_pb2.WriteResponse]]: ...

    @_abc_1.abstractmethod
    def Update(
        self,
        request: _records_pb2.UpdateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.WriteResponse, _abc.Awaitable[_records_pb2.WriteResponse]]: ...

    @_abc_1.abstractmethod
    def Delete(
        self,
        request: _records_pb2.DeleteRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.WriteResponse, _abc.Awaitable[_records_pb2.WriteResponse]]: ...

    @_abc_1.abstractmethod
    def DeleteWhere(
        self,
        request: _records_pb2.DeleteWhereRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.WriteResponse, _abc.Awaitable[_records_pb2.WriteResponse]]:
        """Predicate writes: one statement rather than a query, a round trip and a
        write per row. Both go to the writer, like every other write.
        """

    @_abc_1.abstractmethod
    def UpdateWhere(
        self,
        request: _records_pb2.UpdateWhereRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.WriteResponse, _abc.Awaitable[_records_pb2.WriteResponse]]: ...

    @_abc_1.abstractmethod
    def Batch(
        self,
        request: _records_pb2.BatchRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.BatchResponse, _abc.Awaitable[_records_pb2.BatchResponse]]:
        """Several writes in one round trip. The caller says whether they are
        independent or atomic; there is no default.
        """

    @_abc_1.abstractmethod
    def Get(
        self,
        request: _records_pb2.GetRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.GetResponse, _abc.Awaitable[_records_pb2.GetResponse]]: ...

    @_abc_1.abstractmethod
    def Query(
        self,
        request: _records_pb2.QueryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_records_pb2.QueryResponse], _abc.AsyncIterator[_records_pb2.QueryResponse]]: ...

    @_abc_1.abstractmethod
    def Join(
        self,
        request: _records_pb2.JoinRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_records_pb2.JoinResponse], _abc.AsyncIterator[_records_pb2.JoinResponse]]: ...

    @_abc_1.abstractmethod
    def Aggregate(
        self,
        request: _records_pb2.AggregateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_records_pb2.AggregateResponse], _abc.AsyncIterator[_records_pb2.AggregateResponse]]: ...

    @_abc_1.abstractmethod
    def Related(
        self,
        request: _records_pb2.RelatedRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.RelatedResponse, _abc.Awaitable[_records_pb2.RelatedResponse]]: ...

    @_abc_1.abstractmethod
    def Explain(
        self,
        request: _records_pb2.ExplainRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.ExplainResponse, _abc.Awaitable[_records_pb2.ExplainResponse]]: ...

    @_abc_1.abstractmethod
    def ExplainJoin(
        self,
        request: _records_pb2.ExplainJoinRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.JoinExplainResponse, _abc.Awaitable[_records_pb2.JoinExplainResponse]]: ...

    @_abc_1.abstractmethod
    def ExplainAggregate(
        self,
        request: _records_pb2.ExplainAggregateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.AggregateExplainResponse, _abc.Awaitable[_records_pb2.AggregateExplainResponse]]: ...

    @_abc_1.abstractmethod
    def Leadership(
        self,
        request: _records_pb2.LeadershipRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_records_pb2.LeadershipStatus, _abc.Awaitable[_records_pb2.LeadershipStatus]]: ...

def add_RecordsServicer_to_server(servicer: RecordsServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
