// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: slate/v1/records.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Records_Begin_FullMethodName            = "/slate.v1.Records/Begin"
	Records_Commit_FullMethodName           = "/slate.v1.Records/Commit"
	Records_Rollback_FullMethodName         = "/slate.v1.Records/Rollback"
	Records_Insert_FullMethodName           = "/slate.v1.Records/Insert"
	Records_Update_FullMethodName           = "/slate.v1.Records/Update"
	Records_Delete_FullMethodName           = "/slate.v1.Records/Delete"
	Records_DeleteWhere_FullMethodName      = "/slate.v1.Records/DeleteWhere"
	Records_UpdateWhere_FullMethodName      = "/slate.v1.Records/UpdateWhere"
	Records_Get_FullMethodName              = "/slate.v1.Records/Get"
	Records_Query_FullMethodName            = "/slate.v1.Records/Query"
	Records_Join_FullMethodName             = "/slate.v1.Records/Join"
	Records_Aggregate_FullMethodName        = "/slate.v1.Records/Aggregate"
	Records_Related_FullMethodName          = "/slate.v1.Records/Related"
	Records_Explain_FullMethodName          = "/slate.v1.Records/Explain"
	Records_ExplainJoin_FullMethodName      = "/slate.v1.Records/ExplainJoin"
	Records_ExplainAggregate_FullMethodName = "/slate.v1.Records/ExplainAggregate"
	Records_Leadership_FullMethodName       = "/slate.v1.Records/Leadership"
)

// RecordsClient is the client API for Records service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordsClient interface {
	Begin(ctx context.Context, in *BeginRequest, opts ...grpc.CallOption) (*BeginResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	// Predicate writes: one statement rather than a query, a round trip and a
	// write per row. Both go to the writer, like every other write.
	DeleteWhere(ctx context.Context, in *DeleteWhereRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	UpdateWhere(ctx context.Context, in *UpdateWhereRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error)
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JoinResponse], error)
	Aggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AggregateResponse], error)
	Related(ctx context.Context, in *RelatedRequest, opts ...grpc.CallOption) (*RelatedResponse, error)
	Explain(ctx context.Context, in *ExplainRequest, opts ...grpc.CallOption) (*ExplainResponse, error)
	ExplainJoin(ctx context.Context, in *ExplainJoinRequest, opts ...grpc.CallOption) (*JoinExplainResponse, error)
	ExplainAggregate(ctx context.Context, in *ExplainAggregateRequest, opts ...grpc.CallOption) (*AggregateExplainResponse, error)
	Leadership(ctx context.Context, in *LeadershipRequest, opts ...grpc.CallOption) (*LeadershipStatus, error)
}

type recordsClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordsClient(cc grpc.ClientConnInterface) RecordsClient {
	return &recordsClient{cc}
}

func (c *recordsClient) Begin(ctx context.Context, in *BeginRequest, opts ...grpc.CallOption) (*BeginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginResponse)
	err := c.cc.Invoke(ctx, Records_Begin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, Records_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, Records_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, Records_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, Records_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, Records_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) DeleteWhere(ctx context.Context, in *DeleteWhereRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, Records_DeleteWhere_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) UpdateWhere(ctx context.Context, in *UpdateWhereRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, Records_UpdateWhere_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Records_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Records_ServiceDesc.Streams[0], Records_Query_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Records_QueryClient = grpc.ServerStreamingClient[QueryResponse]

func (c *recordsClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JoinResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Records_ServiceDesc.Streams[1], Records_Join_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JoinRequest, JoinResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Records_JoinClient = grpc.ServerStreamingClient[JoinResponse]

func (c *recordsClient) Aggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AggregateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Records_ServiceDesc.Streams[2], Records_Aggregate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AggregateRequest, AggregateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Records_AggregateClient = grpc.ServerStreamingClient[AggregateResponse]

func (c *recordsClient) Related(ctx context.Context, in *RelatedRequest, opts ...grpc.CallOption) (*RelatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelatedResponse)
	err := c.cc.Invoke(ctx, Records_Related_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) Explain(ctx context.Context, in *ExplainRequest, opts ...grpc.CallOption) (*ExplainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainResponse)
	err := c.cc.Invoke(ctx, Records_Explain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) ExplainJoin(ctx context.Context, in *ExplainJoinRequest, opts ...grpc.CallOption) (*JoinExplainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinExplainResponse)
	err := c.cc.Invoke(ctx, Records_ExplainJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) ExplainAggregate(ctx context.Context, in *ExplainAggregateRequest, opts ...grpc.CallOption) (*AggregateExplainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregateExplainResponse)
	err := c.cc.Invoke(ctx, Records_ExplainAggregate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) Leadership(ctx context.Context, in *LeadershipRequest, opts ...grpc.CallOption) (*LeadershipStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeadershipStatus)
	err := c.cc.Invoke(ctx, Records_Leadership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordsServer is the server API for Records service.
// All implementations must embed UnimplementedRecordsServer
// for forward compatibility.
type RecordsServer interface {
	Begin(context.Context, *BeginRequest) (*BeginResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	Insert(context.Context, *InsertRequest) (*WriteResponse, error)
	Update(context.Context, *UpdateRequest) (*WriteResponse, error)
	Delete(context.Context, *DeleteRequest) (*WriteResponse, error)
	// Predicate writes: one statement rather than a query, a round trip and a
	// write per row. Both go to the writer, like every other write.
	DeleteWhere(context.Context, *DeleteWhereRequest) (*WriteResponse, error)
	UpdateWhere(context.Context, *UpdateWhereRequest) (*WriteResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Query(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error
	Join(*JoinRequest, grpc.ServerStreamingServer[JoinResponse]) error
	Aggregate(*AggregateRequest, grpc.ServerStreamingServer[AggregateResponse]) error
	Related(context.Context, *RelatedRequest) (*RelatedResponse, error)
	Explain(context.Context, *ExplainRequest) (*ExplainResponse, error)
	ExplainJoin(context.Context, *ExplainJoinRequest) (*JoinExplainResponse, error)
	ExplainAggregate(context.Context, *ExplainAggregateRequest) (*AggregateExplainResponse, error)
	Leadership(context.Context, *LeadershipRequest) (*LeadershipStatus, error)
	mustEmbedUnimplementedRecordsServer()
}

// UnimplementedRecordsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordsServer struct{}

func (UnimplementedRecordsServer) Begin(context.Context, *BeginRequest) (*BeginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Begin not implemented")
}
func (UnimplementedRecordsServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedRecordsServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedRecordsServer) Insert(context.Context, *InsertRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedRecordsServer) Update(context.Context, *UpdateRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedRecordsServer) Delete(context.Context, *DeleteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRecordsServer) DeleteWhere(context.Context, *DeleteWhereRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWhere not implemented")
}
func (UnimplementedRecordsServer) UpdateWhere(context.Context, *UpdateWhereRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWhere not implemented")
}
func (UnimplementedRecordsServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRecordsServer) Query(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error {
	return status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedRecordsServer) Join(*JoinRequest, grpc.ServerStreamingServer[JoinResponse]) error {
	return status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedRecordsServer) Aggregate(*AggregateRequest, grpc.ServerStreamingServer[AggregateResponse]) error {
	return status.Error(codes.Unimplemented, "method Aggregate not implemented")
}
func (UnimplementedRecordsServer) Related(context.Context, *RelatedRequest) (*RelatedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Related not implemented")
}
func (UnimplementedRecordsServer) Explain(context.Context, *ExplainRequest) (*ExplainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Explain not implemented")
}
func (UnimplementedRecordsServer) ExplainJoin(context.Context, *ExplainJoinRequest) (*JoinExplainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainJoin not implemented")
}
func (UnimplementedRecordsServer) ExplainAggregate(context.Context, *ExplainAggregateRequest) (*AggregateExplainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainAggregate not implemented")
}
func (UnimplementedRecordsServer) Leadership(context.Context, *LeadershipRequest) (*LeadershipStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Leadership not implemented")
}
func (UnimplementedRecordsServer) mustEmbedUnimplementedRecordsServer() {}
func (UnimplementedRecordsServer) testEmbeddedByValue()                 {}

// UnsafeRecordsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordsServer will
// result in compilation errors.
type UnsafeRecordsServer interface {
	mustEmbedUnimplementedRecordsServer()
}

func RegisterRecordsServer(s grpc.ServiceRegistrar, srv RecordsServer) {
	// If the following call panics, it indicates UnimplementedRecordsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Records_ServiceDesc, srv)
}

func _Records_Begin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).Begin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_Begin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).Begin(ctx, req.(*BeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_DeleteWhere_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWhereRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).DeleteWhere(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_DeleteWhere_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).DeleteWhere(ctx, req.(*DeleteWhereRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_UpdateWhere_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWhereRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).UpdateWhere(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_UpdateWhere_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).UpdateWhere(ctx, req.(*UpdateWhereRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecordsServer).Query(m, &grpc.GenericServerStream[QueryRequest, QueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Records_QueryServer = grpc.ServerStreamingServer[QueryResponse]

func _Records_Join_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecordsServer).Join(m, &grpc.GenericServerStream[JoinRequest, JoinResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Records_JoinServer = grpc.ServerStreamingServer[JoinResponse]

func _Records_Aggregate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AggregateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecordsServer).Aggregate(m, &grpc.GenericServerStream[AggregateRequest, AggregateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Records_AggregateServer = grpc.ServerStreamingServer[AggregateResponse]

func _Records_Related_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).Related(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_Related_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).Related(ctx, req.(*RelatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_Explain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).Explain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_Explain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).Explain(ctx, req.(*ExplainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_ExplainJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).ExplainJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_ExplainJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).ExplainJoin(ctx, req.(*ExplainJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_ExplainAggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainAggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).ExplainAggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_ExplainAggregate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).ExplainAggregate(ctx, req.(*ExplainAggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_Leadership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeadershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).Leadership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_Leadership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).Leadership(ctx, req.(*LeadershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Records_ServiceDesc is the grpc.ServiceDesc for Records service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Records_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slate.v1.Records",
	HandlerType: (*RecordsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Begin",
			Handler:    _Records_Begin_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Records_Commit_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _Records_Rollback_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _Records_Insert_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Records_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Records_Delete_Handler,
		},
		{
			MethodName: "DeleteWhere",
			Handler:    _Records_DeleteWhere_Handler,
		},
		{
			MethodName: "UpdateWhere",
			Handler:    _Records_UpdateWhere_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Records_Get_Handler,
		},
		{
			MethodName: "Related",
			Handler:    _Records_Related_Handler,
		},
		{
			MethodName: "Explain",
			Handler:    _Records_Explain_Handler,
		},
		{
			MethodName: "ExplainJoin",
			Handler:    _Records_ExplainJoin_Handler,
		},
		{
			MethodName: "ExplainAggregate",
			Handler:    _Records_ExplainAggregate_Handler,
		},
		{
			MethodName: "Leadership",
			Handler:    _Records_Leadership_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _Records_Query_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Join",
			Handler:       _Records_Join_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Aggregate",
			Handler:       _Records_Aggregate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "slate/v1/records.proto",
}
