#!/usr/bin/env node
// Write the protocol's codecs as static code, so no runtime has to compile
// them — `docs/edge-client.md` §3.
//
//     node scripts/generate-codecs.mjs           # write them
//     node scripts/generate-codecs.mjs --check   # exit 1 if any is stale
//
// **Static, not reflected.** protobufjs's usual mode builds each message's
// encoder and decoder at runtime with `new Function`, and Cloudflare Workers
// refuse that: every request the edge adapter made failed with "Code
// generation from strings disallowed for this context", while the whole
// suite passed over gRPC-web in Node, where it is allowed. `pbjs -t
// static-module` writes the same functions out as source instead.
//
// Three files:
//
// - `src/generated/records.ts` — `records.proto`, camelCase, as
//   `@grpc/proto-loader` loads it for the native transport (`keepCase: false`);
// - `src/generated/status.ts` — the two `google/rpc` files, keeping case, as
//   `details.ts` always read them (`Any.type_url`);
// - `src/descriptor.ts` — each RPC's request and response type, and whether it
//   streams, which is all the transport needs to know about the service.
//
// `pbjs` is pinned exactly in `package.json`: it generates committed code, and
// a range would put the output on its release calendar.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import protobuf from "protobufjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.dirname(here);
const protoRoot = path.join(packageRoot, "proto");
const pbjs = path.join(packageRoot, "node_modules", ".bin", "pbjs");

function staticModule(files, keepCase) {
  const out = execFileSync(
    pbjs,
    [
      "-t", "static-module", "-w", "es6", "-p", protoRoot,
      "--no-comments", "--no-create", "--no-verify", "--no-delimited", "--no-service",
      ...(keepCase ? ["--keep-case"] : []),
      ...files,
    ],
    { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
  );
  // A default import of the CommonJS `protobufjs/minimal`, with its extension:
  // under Node's ESM a namespace import gives the module namespace rather than
  // `module.exports`, which `details.ts` records costing a day once already,
  // and an extensionless subpath does not resolve at all.
  const fixed = out.replace(
    'import * as $protobuf from "protobufjs/minimal";',
    'import $protobuf from "protobufjs/minimal.js";',
  );
  if (fixed === out) throw new Error("pbjs output no longer imports protobufjs/minimal as expected");
  return (
    "// @ts-nocheck\n" +
    "// Generated by `scripts/generate-codecs.mjs` from `proto/`. Do not edit:\n" +
    "// `test/descriptor.test.ts` regenerates it and fails if it differs.\n" +
    fixed
  );
}

function methods() {
  const root = new protobuf.Root();
  root.resolvePath = (_origin, file) => path.join(protoRoot, file);
  root.loadSync("slate/v1/records.proto", { keepCase: false });
  root.resolveAll();
  const service = root.lookupService("slate.v1.Records");
  const table = {};
  for (const [name, m] of Object.entries(service.methods)) {
    if (m.requestStream) throw new Error(`${name} streams its request; gRPC-web cannot carry that`);
    table[name] = [
      m.resolvedRequestType.fullName.replace(/^\./, ""),
      m.resolvedResponseType.fullName.replace(/^\./, ""),
      m.responseStream === true,
    ];
  }
  return (
    "// Generated by `scripts/generate-codecs.mjs` from `proto/`. Do not edit:\n" +
    "// `test/descriptor.test.ts` regenerates it and fails if it differs.\n" +
    "/** Each RPC: its request type, its response type, and whether the response streams. */\n" +
    `export const METHODS: Record<string, readonly [string, string, boolean]> = ${JSON.stringify(table, null, 2)};\n`
  );
}

const outputs = {
  [path.join(packageRoot, "src", "generated", "records.ts")]: staticModule(["slate/v1/records.proto"], false),
  [path.join(packageRoot, "src", "generated", "status.ts")]: staticModule(
    ["google/rpc/status.proto", "google/rpc/error_details.proto"],
    true,
  ),
  [path.join(packageRoot, "src", "descriptor.ts")]: methods(),
};

if (process.argv.includes("--check")) {
  const stale = Object.entries(outputs).filter(([file, text]) => {
    try {
      return readFileSync(file, "utf8") !== text;
    } catch {
      return true;
    }
  });
  if (stale.length) {
    for (const [file] of stale) console.error(`stale: ${path.relative(packageRoot, file)}`);
    console.error("The generated codecs do not match proto/. Run `node scripts/generate-codecs.mjs`.");
    process.exit(1);
  }
  console.log(`ok    ${Object.keys(outputs).length} generated files match proto/`);
} else {
  mkdirSync(path.join(packageRoot, "src", "generated"), { recursive: true });
  for (const [file, text] of Object.entries(outputs)) {
    writeFileSync(file, text);
    console.log(`wrote ${path.relative(packageRoot, file)} (${text.length} bytes)`);
  }
}
