// Generated by `scripts/generate-codecs.mjs` from `proto/`. Do not edit:
// `test/descriptor.test.ts` regenerates it and fails if it differs.
/** Each RPC: its request type, its response type, and whether the response streams. */
export const METHODS: Record<string, readonly [string, string, boolean]> = {
  "Begin": [
    "slate.v1.BeginRequest",
    "slate.v1.BeginResponse",
    false
  ],
  "Commit": [
    "slate.v1.CommitRequest",
    "slate.v1.CommitResponse",
    false
  ],
  "Rollback": [
    "slate.v1.RollbackRequest",
    "slate.v1.RollbackResponse",
    false
  ],
  "Insert": [
    "slate.v1.InsertRequest",
    "slate.v1.WriteResponse",
    false
  ],
  "Update": [
    "slate.v1.UpdateRequest",
    "slate.v1.WriteResponse",
    false
  ],
  "Delete": [
    "slate.v1.DeleteRequest",
    "slate.v1.WriteResponse",
    false
  ],
  "DeleteWhere": [
    "slate.v1.DeleteWhereRequest",
    "slate.v1.WriteResponse",
    false
  ],
  "UpdateWhere": [
    "slate.v1.UpdateWhereRequest",
    "slate.v1.WriteResponse",
    false
  ],
  "PurgeDeleted": [
    "slate.v1.PurgeDeletedRequest",
    "slate.v1.WriteResponse",
    false
  ],
  "Batch": [
    "slate.v1.BatchRequest",
    "slate.v1.BatchResponse",
    false
  ],
  "Get": [
    "slate.v1.GetRequest",
    "slate.v1.GetResponse",
    false
  ],
  "Query": [
    "slate.v1.QueryRequest",
    "slate.v1.QueryResponse",
    true
  ],
  "Join": [
    "slate.v1.JoinRequest",
    "slate.v1.JoinResponse",
    true
  ],
  "Aggregate": [
    "slate.v1.AggregateRequest",
    "slate.v1.AggregateResponse",
    true
  ],
  "Related": [
    "slate.v1.RelatedRequest",
    "slate.v1.RelatedResponse",
    false
  ],
  "Explain": [
    "slate.v1.ExplainRequest",
    "slate.v1.ExplainResponse",
    false
  ],
  "ExplainJoin": [
    "slate.v1.ExplainJoinRequest",
    "slate.v1.JoinExplainResponse",
    false
  ],
  "ExplainAggregate": [
    "slate.v1.ExplainAggregateRequest",
    "slate.v1.AggregateExplainResponse",
    false
  ],
  "Leadership": [
    "slate.v1.LeadershipRequest",
    "slate.v1.LeadershipStatus",
    false
  ]
};
