"""The server's tables, as this client must declare them.

Generated by scripts/codegen.py. Do not edit.

A client holds its own copy of the schema and the server checks it:
every request carries a fingerprint, and a declaration that disagrees
with the catalog is refused rather than answered positionally-wrong.
This file is that declaration, produced from the catalog itself so the
two cannot drift.
"""

from __future__ import annotations

from slate import Column, Table, ValueType

__all__ = [
    "AUTHORS",
    "BOOKS",
    "BY_NAME",
    "EDITIONS",
    "SALES",
]

AUTHORS = Table(
    "authors",
    [
        Column("id", ValueType.U64),
        Column("name", ValueType.STR),
        Column("country", ValueType.STR),
        Column("born", ValueType.I64),
    ],
    primary_key=["id"],
)

BOOKS = Table(
    "books",
    [
        Column("id", ValueType.U64),
        Column("author_id", ValueType.U64),
        Column("title", ValueType.STR),
        Column("year", ValueType.I64),
        Column("rating", ValueType.F64),
        Column("released", ValueType.I64),
        Column("embedding", ValueType.VECTOR),
        Column("price", ValueType.DECIMAL, scale=2),
    ],
    primary_key=["id"],
)

SALES = Table(
    "sales",
    [
        Column("id", ValueType.U64),
        Column("book_id", ValueType.U64),
        Column("units", ValueType.I64),
    ],
    primary_key=["id"],
)

EDITIONS = Table(
    "editions",
    [
        Column("id", ValueType.U64),
        Column("book_id", ValueType.U64),
        Column("format", ValueType.STR),
    ],
    primary_key=["id"],
)

BY_NAME = {table.name: table for table in (AUTHORS, BOOKS, SALES, EDITIONS,)}
