#!/usr/bin/env python3
"""The docs site holds together: links resolve, and the two navigations agree.

    python3 site/check/docs.py

The sidebar is stated once, in `site/docs/nav.js`, and rendered by script. Every
page also carries a `<noscript>` copy as plain markup — which is a *second*
statement of the same list, and therefore exactly the thing this repository
keeps finding stale. This check is the reason that duplication is allowed: the
two are compared here, in order, link for link and label for label.

The rest is link rot. A static site has no compiler, so a page renamed in one
place and linked from three others fails nowhere until a reader clicks. Every
relative `href` and `src` in every HTML file under `site/` is resolved against
the filesystem, and a miss is a failure.

Deliberately not checked: anything that needs a browser. `site/check/workbench.py`
owns that, and it is slow; this runs in well under a second and can be run on
every save.
"""

from __future__ import annotations

import re
import sys
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urldefrag

ROOT = Path(__file__).resolve().parents[2]
SITE = ROOT / "site"
DOCS = SITE / "docs"
NAV = DOCS / "nav.js"

failures: list[str] = []

#: Tags that never close. Treating one as an open element is how a checker
#: reports every page as broken from its first `<meta>` onward.
VOID = {
    "area", "base", "br", "col", "embed", "hr", "img", "input",
    "link", "meta", "param", "source", "track", "wbr",
}


class Nesting(HTMLParser):
    """Every element closes, and closes the one it opened.

    Worth having because an unbalanced `<div>` does not fail anywhere: the
    browser repairs it, silently and differently from how the author meant, and
    the page renders *nearly* right. The pages here were generated by a script
    that got this wrong once — a stray `</div>` closed the snippet wrapper early
    — and nothing but reading the markup found it.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.stack: list[tuple[str, int]] = []
        self.problems: list[str] = []

    def handle_starttag(self, tag: str, attrs: object) -> None:
        if tag not in VOID:
            self.stack.append((tag, self.getpos()[0]))

    def handle_endtag(self, tag: str) -> None:
        if tag in VOID:
            return
        if not self.stack:
            self.problems.append(f"line {self.getpos()[0]}: </{tag}> with nothing open")
            return
        top, opened = self.stack[-1]
        if top != tag:
            self.problems.append(
                f"line {self.getpos()[0]}: </{tag}> closes <{top}> opened at line {opened}"
            )
            # Unwind to it anyway, so one mistake reports once rather than
            # cascading into every tag after it.
            if any(t == tag for t, _ in self.stack):
                while self.stack and self.stack[-1][0] != tag:
                    self.stack.pop()
                self.stack.pop()
            return
        self.stack.pop()

    def report(self) -> list[str]:
        return self.problems + [
            f"<{tag}> opened at line {line} never closes" for tag, line in self.stack
        ]


def check(what: str, ok: bool, detail: str = "") -> None:
    if ok:
        print(f"ok    {what}")
    else:
        print(f"FAIL  {what}" + (f"\n      {detail}" if detail else ""))
        failures.append(what)


def nav_sections() -> list[tuple[str, list[tuple[str, str]]]]:
    """`SECTIONS` out of `nav.js`, in order.

    Read with a regex rather than by executing the module, because the point is
    to compare what the file *says* against what the pages say. Running it would
    need a JavaScript engine to check a list of strings.
    """
    source = NAV.read_text()
    start = source.index("export const SECTIONS = [")
    end = source.index("\n];", start)
    body = source[start:end]

    sections: list[tuple[str, list[tuple[str, str]]]] = []
    # Each `{ title: "…", pages: [ ["href", "Label"], … ] }`.
    for block in re.finditer(
        r'title:\s*"([^"]+)",\s*pages:\s*\[(.*?)\],\s*\n\s*\}', body, re.S
    ):
        pages = re.findall(r'\["([^"]+)",\s*"([^"]+)"\]', block.group(2))
        sections.append((block.group(1), pages))
    return sections


def noscript_sections(page: Path) -> list[tuple[str, list[tuple[str, str]]]]:
    """The same list, as the `<noscript>` block on one page spells it."""
    text = page.read_text()
    block = re.search(r"<noscript>(.*?)</noscript>", text, re.S)
    if not block:
        return []
    out: list[tuple[str, list[tuple[str, str]]]] = []
    # Split on the section headings, keeping each heading with what follows it.
    parts = re.split(r'<h2 class="nav-section">([^<]+)</h2>', block.group(1))
    # `strict=True`: `re.split` with one capture group yields a heading and
    # the chunk after it in strict alternation, so the two slices are always
    # the same length. If they ever are not, the pattern has changed and a
    # silently truncated navigation is the worst way to find out.
    for title, chunk in zip(parts[1::2], parts[2::2], strict=True):
        pages = re.findall(r'<a href="([^"]+)">([^<]+)</a>', chunk)
        out.append((title, pages))
    return out


def main() -> int:
    sections = nav_sections()
    listed = [href for _, pages in sections for href, _ in pages]

    check(
        "nav.js declares a sidebar at all",
        len(sections) >= 2 and len(listed) >= 4,
        f"parsed {len(sections)} sections, {len(listed)} pages",
    )

    # Every listed page exists, and every page on disk is listed. The second
    # half is the one that matters: a page nobody links is a page nobody reads
    # and nobody notices has rotted.
    missing = [href for href in listed if not (DOCS / href).exists()]
    check("every page the sidebar lists exists", not missing, ", ".join(missing))

    on_disk = {p.name for p in DOCS.glob("*.html")}
    orphans = sorted(on_disk - set(listed))
    check("every page on disk is in the sidebar", not orphans, ", ".join(orphans))

    # The two navigations agree, in order.
    for name in sorted(on_disk):
        page = DOCS / name
        fallback = noscript_sections(page)
        check(
            f"{name}: the noscript sidebar matches nav.js",
            fallback == sections,
            f"nav.js has {sections}\n      {name} has {fallback}",
        )

    # Every page loads the shared theme, the docs stylesheet and the nav module.
    for name in sorted(on_disk):
        text = (DOCS / name).read_text()
        wants = ["../theme.css", "docs.css", "nav.js"]
        absent = [w for w in wants if w not in text]
        check(f"{name}: loads the shared theme and nav", not absent, ", ".join(absent))

    # Every page's markup is balanced.
    for page in sorted(SITE.rglob("*.html")):
        if "node_modules" in page.parts:
            continue
        parser = Nesting()
        parser.feed(page.read_text())
        problems = parser.report()
        check(
            f"{page.relative_to(SITE)}: every element closes the one it opened",
            not problems,
            "\n      ".join(problems[:6]),
        )

    # Link rot, across the whole site.
    broken: list[str] = []
    for page in sorted(SITE.rglob("*.html")):
        if "node_modules" in page.parts:
            continue
        for attribute in re.findall(r'(?:href|src)="([^"]+)"', page.read_text()):
            target = urldefrag(attribute).url
            if not target or target.startswith(("http://", "https://", "data:", "#", "mailto:")):
                continue
            resolved = (page.parent / target).resolve()
            if not resolved.exists():
                broken.append(f"{page.relative_to(ROOT)} → {target}")
    check("every relative link resolves to a file", not broken, "\n      ".join(broken))

    print()
    if failures:
        print(f"{len(failures)} failed")
        return 1
    print("the docs site holds together")
    return 0


if __name__ == "__main__":
    sys.exit(main())
