"""The server's tables, as this client must declare them.

Generated by scripts/codegen.py. Do not edit.

A client holds its own copy of the schema and the server checks it:
every request carries a fingerprint, and a declaration that disagrees
with the catalog is refused rather than answered positionally-wrong.
This file is that declaration, produced from the catalog itself so the
two cannot drift.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import cast

from slate import Column, Table, ValueType
from slate.values import NULL, Null, i64, u64

__all__ = [
    "BY_NAME",
    "NOTES",
    "Notes",
]

NOTES = Table(
    "notes",
    [
        Column("id", ValueType.U64),
        Column("body", ValueType.STR),
        Column("deleted_at", ValueType.I64),
    ],
    primary_key=["id"],
)

BY_NAME = {table.name: table for table in (NOTES,)}


def _field(values: Sequence[object], at: int, table: str, column: str,
           kind: type | tuple[type, ...], nullable: bool) -> object:
    """One column of a row, checked.

    The check is the point. Python would happily hand back whatever sat
    at the ordinal, and a declaration that is one column out reads the
    neighbour and looks plausible — which is the failure this whole
    generator exists to make impossible. Raising here names the table
    and the column, so the error says where to look.
    """
    value = values[at]
    if value is None or isinstance(value, Null):
        if nullable:
            return None
        raise ValueError(
            f"{table}.{column} is not nullable and came back null"
        )
    if not isinstance(value, kind):
        raise TypeError(
            f"{table}.{column} is {type(value).__name__}, "
            f"not the declared {kind}"
        )
    return value


@dataclass(frozen=True)
class Notes:
    """A row of `notes`, decoded."""

    id: int
    body: str
    deleted_at: int | None

    @classmethod
    def from_row(cls, values: Sequence[object]) -> Notes:
        """Decode a row of `notes`, by ordinal."""
        if len(values) != 3:
            raise ValueError(
                f"notes has 3 columns, got {len(values)}"
            )
        return cls(
            id=cast("int", _field(values, 0, "notes", "id", int, False)),
            body=cast("str", _field(values, 1, "notes", "body", str, False)),
            deleted_at=cast("int | None", _field(values, 2, "notes", "deleted_at", int, True)),
        )

    def to_row(self) -> list[object]:
        """Encode this row in the column order of `notes`."""
        return [
            u64(self.id),
            self.body,
            NULL if self.deleted_at is None else i64(self.deleted_at),
        ]

    @property
    def retired(self) -> bool:
        """Whether this row has been soft-deleted."""
        return self.deleted_at is not None
