//! The real dataset, checked against itself.
//!
//! These run against the committed `site/data/trips.bin.gz` — the bytes the
//! browser downloads — rather than a fixture built here. That is the point:
//! the file is data, it is not regenerated by the build, and nothing else
//! would notice if it were replaced by 1.2 MB of zeroes.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic
)]

use serde_json::{Value as Json, json};
use slate_wasm::{Playground, taxi};
use std::io::Read;
use std::path::PathBuf;

fn trip_bytes() -> Vec<u8> {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "site",
        "data",
        "trips.bin.gz",
    ]
    .iter()
    .collect();
    let file = std::fs::File::open(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    // A three-line gzip reader rather than a dependency: the format's fixed
    // header, and `flate2` is not otherwise in this crate's tree.
    let mut decoder = flate2::read::GzDecoder::new(file);
    let mut out = Vec::new();
    decoder
        .read_to_end(&mut out)
        .expect("the trip file is gzip");
    out
}

fn loaded() -> Playground {
    let mut playground = Playground::new();
    let outcome: Json = serde_json::from_str(&playground.load_trips(&trip_bytes())).expect("JSON");
    assert_eq!(outcome["ok"], json!(100_000), "{outcome}");
    playground
}

fn sql(playground: &Playground, text: &str) -> Json {
    let all: Vec<Json> = serde_json::from_str(&playground.sql(text)).expect("JSON");
    let last = all.last().expect("a result").clone();
    assert!(last["error"].is_null(), "{text}: {}", last["error"]);
    last
}

#[test]
fn the_committed_file_decodes_to_the_month_it_claims() {
    let rows = taxi::decode(&trip_bytes()).expect("decode");
    assert_eq!(rows.len(), 100_000);

    // January 2024, and nothing outside it. The source file really does carry
    // trips stamped 2002 and 2009; the sampler drops them, and this is what
    // says so rather than trusting that it did.
    const START: i64 = 1_704_067_200; // 2024-01-01T00:00:00Z
    const END: i64 = START + 31 * 86_400;
    let times: Vec<i64> = rows
        .iter()
        .map(|r| match r.values()[3] {
            slate_tuple::Value::I64(n) => n,
            ref other => panic!("pickup_time is {other:?}"),
        })
        .collect();
    assert!(
        times.iter().all(|t| (START..END).contains(t)),
        "outside January"
    );

    // Spread across the whole month, not the first hours of it. The sampler
    // had exactly that bug: it sorted candidate indices and stopped at the
    // sample size, which took a prefix of the file — New Year's Day.
    let days: std::collections::BTreeSet<i64> =
        times.iter().map(|t| (t - START) / 86_400).collect();
    assert_eq!(days.len(), 31, "only {} days covered", days.len());
}

#[test]
fn the_real_nulls_survive_the_round_trip() {
    let rows = taxi::decode(&trip_bytes()).expect("decode");
    let missing = rows
        .iter()
        .filter(|r| matches!(r.values()[5], slate_tuple::Value::Null))
        .count();
    // 4.73% of the month has no passenger count. Filling those in would have
    // made `count(passengers)` a synonym for `count(*)`, which is the one
    // distinction the books fixture could not draw.
    assert!(
        (4_000..5_500).contains(&missing),
        "{missing} nulls, expected about 4,700"
    );
}

#[test]
fn count_of_a_nullable_column_is_smaller_than_count_of_rows() {
    let playground = loaded();
    let answer = sql(
        &playground,
        "SELECT payment, count(*), count(passengers) FROM trips GROUP BY payment",
    );
    let rows = answer["rows"].as_array().unwrap();
    assert!(!rows.is_empty());

    let mut saw_difference = false;
    for row in rows {
        let all: u64 = row[1].as_str().unwrap().parse().unwrap();
        let some: u64 = row[2].as_str().unwrap().parse().unwrap();
        assert!(some <= all, "count(passengers) {some} > count(*) {all}");
        saw_difference |= some < all;
    }
    // The assertion the books fixture could not make: these are different
    // aggregates and this data proves it. A binding that folded one into the
    // other passed every test before this one.
    assert!(saw_difference, "no group had a missing passenger count");
}

#[test]
fn the_zones_are_the_tlcs_own_table() {
    let playground = Playground::new();
    let answer = sql(&playground, "SELECT * FROM zones LIMIT 300");
    assert_eq!(
        answer["returned"],
        json!(265),
        "the TLC publishes 265 zones"
    );

    let manhattan = sql(
        &playground,
        "SELECT borough, count(*) FROM zones GROUP BY borough",
    );
    let boroughs: Vec<String> = manhattan["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|r| r[0].as_str().unwrap().to_owned())
        .collect();
    for borough in ["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"] {
        assert!(
            boroughs.contains(&borough.to_owned()),
            "no {borough} in {boroughs:?}"
        );
    }
}

#[test]
fn a_zone_join_puts_names_on_the_trips() {
    let playground = loaded();
    let answer = sql(
        &playground,
        "SELECT * FROM trips JOIN zones ON trips.pickup_zone = zones.id \
         WHERE trips.pickup_zone = 132 LIMIT 5",
    );
    assert_eq!(answer["kind"], "join");
    let rows = answer["rows"].as_array().unwrap();
    assert_eq!(rows.len(), 5);
    // Zone 132 is JFK Airport, in Queens. A real fact about a real table; if
    // the join keyed the wrong pair of columns this is what would change.
    for row in rows {
        let cells: Vec<&str> = row
            .as_array()
            .unwrap()
            .iter()
            .map(|c| c.as_str().unwrap())
            .collect();
        assert!(cells.contains(&"JFK Airport"), "{cells:?}");
        assert!(cells.contains(&"Queens"), "{cells:?}");
    }
}

#[test]
fn the_clickhouse_taxi_queries_run() {
    let playground = loaded();

    // ClickHouse's published NYC-taxi benchmark is four queries. Three of them
    // are expressible here; the fourth is not, and saying which is the point
    // of writing them down.
    //
    // Q1 `SELECT cab_type, count(*) ... GROUP BY cab_type` — one vendor here,
    // so `payment` stands in as the low-cardinality key. Same shape.
    let q1 = sql(
        &playground,
        "SELECT payment, count(*) FROM trips GROUP BY payment",
    );
    assert!(q1["rows"].as_array().unwrap().len() >= 2);
    let total: u64 = q1["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|r| r[1].as_str().unwrap().parse::<u64>().unwrap())
        .sum();
    assert_eq!(total, 100_000, "every trip lands in exactly one group");

    // Q2 `SELECT passenger_count, avg(total_amount) ... GROUP BY
    // passenger_count` — verbatim, modulo column names.
    let q2 = sql(
        &playground,
        "SELECT passengers, avg(total) FROM trips GROUP BY passengers",
    );
    assert!(q2["rows"].as_array().unwrap().len() >= 5);

    // Q3 adds the pickup year to the key. There is no date type and no
    // `toYear`, and one month of data has one year in it, so the closest
    // honest thing is a second key that varies: the zone.
    let q3 = sql(
        &playground,
        "SELECT pickup_zone, passengers, count(*) FROM trips GROUP BY pickup_zone, passengers",
    );
    assert!(q3["rows"].as_array().unwrap().len() > 100);

    // Q4 sorts the groups by count descending and takes the top of them. This
    // is the query the whole ordered-grouping path exists for, and the one a
    // reader is most likely to write: *where do most taxis pick up?*
    let q4 = sql(
        &playground,
        "SELECT pickup_zone, count(*) FROM trips GROUP BY pickup_zone \
         ORDER BY count(*) DESC LIMIT 10",
    );
    let rows = q4["rows"].as_array().unwrap();
    assert_eq!(rows.len(), 10, "LIMIT applies to the groups, not the rows");
    let counts: Vec<u64> = rows
        .iter()
        .map(|r| r[1].as_str().unwrap().parse().unwrap())
        .collect();
    assert!(
        counts.windows(2).all(|w| w[0] >= w[1]),
        "groups are not in descending order: {counts:?}"
    );
    // The busiest zone in a real month of yellow-taxi pickups has thousands of
    // trips, not the ~440 an even spread over 226 zones would give. If this
    // ever comes back flat, the ordering is not doing anything.
    assert!(
        counts[0] > 1_000,
        "busiest zone had only {} trips",
        counts[0]
    );
}

#[test]
fn a_filter_on_the_indexed_zone_is_a_real_planner_decision() {
    let playground = loaded();
    // 100,000 rows over 226 zones: a few hundred rows a zone. The index can
    // answer it covering, and cannot pay for itself when rows must be fetched.
    let covering = sql(
        &playground,
        "SELECT pickup_zone FROM trips WHERE pickup_zone = 132",
    );
    assert_eq!(
        covering["plan"]["indexOnly"],
        json!(true),
        "{}",
        covering["plan"]
    );

    let whole = sql(&playground, "SELECT * FROM trips WHERE pickup_zone = 132");
    assert_eq!(whole["plan"]["indexOnly"], json!(false));
    assert_eq!(whole["returned"], covering["returned"]);
}

#[test]
fn every_column_comes_from_the_field_the_format_says_it_does() {
    let bytes = trip_bytes();
    let rows = taxi::decode(&bytes).expect("decode");

    // Unpack the first three records straight from the documented layout in
    // `site/data/make-trips.py` and compare field for field.
    //
    // This exists because a mutation that read the *dropoff* zone into the
    // pickup column changed no test: the join test filters on pickup_zone and
    // joins on pickup_zone, so a consistently wrong column still finds rows
    // and still resolves 132 to JFK. Only an independent reading of the bytes
    // can tell one field from another.
    const BASE: i64 = 1_704_067_200;
    for (i, row) in rows.iter().take(3).enumerate() {
        let r = &bytes[i * 24..(i + 1) * 24];
        let u16_at = |o: usize| u16::from_le_bytes([r[o], r[o + 1]]) as i64;
        let i32_at = |o: usize| i32::from_le_bytes([r[o], r[o + 1], r[o + 2], r[o + 3]]) as i64;
        let v = row.values();

        let number = |value: &slate_tuple::Value| -> i64 {
            match value {
                slate_tuple::Value::U64(n) => *n as i64,
                slate_tuple::Value::I64(n) => *n,
                other => panic!("not a number: {other:?}"),
            }
        };
        let float = |value: &slate_tuple::Value| -> f64 {
            match value {
                slate_tuple::Value::F64(n) => *n,
                other => panic!("not a float: {other:?}"),
            }
        };

        assert_eq!(number(&v[0]), i as i64 + 1, "id");
        assert_eq!(number(&v[1]), u16_at(6), "pickup_zone is bytes 6..8");
        assert_eq!(number(&v[2]), u16_at(8), "dropoff_zone is bytes 8..10");
        assert_eq!(number(&v[3]), BASE + i32_at(0), "pickup_time is bytes 0..4");
        assert_eq!(number(&v[4]), u16_at(4), "duration is bytes 4..6");
        assert!(
            (float(&v[6]) - u16_at(11) as f64 / 100.0).abs() < 1e-9,
            "distance"
        );
        assert!(
            (float(&v[7]) - i32_at(13) as f64 / 100.0).abs() < 1e-9,
            "fare"
        );
        assert!(
            (float(&v[8]) - u16_at(17) as f64 / 100.0).abs() < 1e-9,
            "tip"
        );
        assert!(
            (float(&v[9]) - i32_at(19) as f64 / 100.0).abs() < 1e-9,
            "total"
        );
    }

    // And the two zone columns really do carry different data, so a decoder
    // that read one field into both would not slip past the checks above on a
    // trip that happened to start and end in the same zone.
    let same = rows
        .iter()
        .filter(|r| r.values()[1] == r.values()[2])
        .count();
    assert!(
        same < rows.len() / 2,
        "{same} of {} trips start and end in the same zone; the columns look identical",
        rows.len()
    );
}
