//! The real dataset, checked against itself.
//!
//! These run against the committed `site/data/trips.bin.gz` — the bytes the
//! browser downloads — rather than a fixture built here. That is the point:
//! the file is data, it is not regenerated by the build, and nothing else
//! would notice if it were replaced by 1.2 MB of zeroes.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic
)]

use serde_json::{Value as Json, json};
use slate_wasm::{Playground, taxi};
use std::io::Read;
use std::path::PathBuf;

fn trip_bytes() -> Vec<u8> {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "site",
        "data",
        "trips.bin.gz",
    ]
    .iter()
    .collect();
    let file = std::fs::File::open(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    // A three-line gzip reader rather than a dependency: the format's fixed
    // header, and `flate2` is not otherwise in this crate's tree.
    let mut decoder = flate2::read::GzDecoder::new(file);
    let mut out = Vec::new();
    decoder
        .read_to_end(&mut out)
        .expect("the trip file is gzip");
    out
}

fn loaded() -> Playground {
    let mut playground = Playground::new();
    let outcome: Json = serde_json::from_str(&playground.load_trips(&trip_bytes())).expect("JSON");
    assert_eq!(outcome["ok"], json!(100_000), "{outcome}");
    playground
}

fn sql(playground: &Playground, text: &str) -> Json {
    let all: Vec<Json> = serde_json::from_str(&playground.sql(text)).expect("JSON");
    let last = all.last().expect("a result").clone();
    assert!(last["error"].is_null(), "{text}: {}", last["error"]);
    last
}

#[test]
fn the_committed_file_decodes_to_the_month_it_claims() {
    let rows = taxi::decode(&trip_bytes()).expect("decode");
    assert_eq!(rows.len(), 100_000);

    // January 2024, and nothing outside it. The source file really does carry
    // trips stamped 2002 and 2009; the sampler drops them, and this is what
    // says so rather than trusting that it did.
    const START: i64 = 1_704_067_200; // 2024-01-01T00:00:00Z
    const END: i64 = START + 31 * 86_400;
    let times: Vec<i64> = rows
        .iter()
        .map(|r| match r.values()[3] {
            slate_tuple::Value::I64(n) => n,
            ref other => panic!("pickup_time is {other:?}"),
        })
        .collect();
    assert!(
        times.iter().all(|t| (START..END).contains(t)),
        "outside January"
    );

    // Spread across the whole month, not the first hours of it. The sampler
    // had exactly that bug: it sorted candidate indices and stopped at the
    // sample size, which took a prefix of the file — New Year's Day.
    let days: std::collections::BTreeSet<i64> =
        times.iter().map(|t| (t - START) / 86_400).collect();
    assert_eq!(days.len(), 31, "only {} days covered", days.len());
}

#[test]
fn the_real_nulls_survive_the_round_trip() {
    let rows = taxi::decode(&trip_bytes()).expect("decode");
    let missing = rows
        .iter()
        .filter(|r| matches!(r.values()[5], slate_tuple::Value::Null))
        .count();
    // 4.73% of the month has no passenger count. Filling those in would have
    // made `count(passengers)` a synonym for `count(*)`, which is the one
    // distinction the books fixture could not draw.
    assert!(
        (4_000..5_500).contains(&missing),
        "{missing} nulls, expected about 4,700"
    );
}

#[test]
fn count_of_a_nullable_column_is_smaller_than_count_of_rows() {
    let playground = loaded();
    let answer = sql(
        &playground,
        "SELECT payment, count(*), count(passengers) FROM trips GROUP BY payment",
    );
    let rows = answer["rows"].as_array().unwrap();
    assert!(!rows.is_empty());

    let mut saw_difference = false;
    for row in rows {
        let all: u64 = row[1].as_str().unwrap().parse().unwrap();
        let some: u64 = row[2].as_str().unwrap().parse().unwrap();
        assert!(some <= all, "count(passengers) {some} > count(*) {all}");
        saw_difference |= some < all;
    }
    // The assertion the books fixture could not make: these are different
    // aggregates and this data proves it. A binding that folded one into the
    // other passed every test before this one.
    assert!(saw_difference, "no group had a missing passenger count");
}

#[test]
fn the_zones_are_the_tlcs_own_table() {
    let playground = Playground::new();
    let answer = sql(&playground, "SELECT * FROM zones LIMIT 300");
    assert_eq!(
        answer["returned"],
        json!(265),
        "the TLC publishes 265 zones"
    );

    let manhattan = sql(
        &playground,
        "SELECT borough, count(*) FROM zones GROUP BY borough",
    );
    let boroughs: Vec<String> = manhattan["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|r| r[0].as_str().unwrap().to_owned())
        .collect();
    for borough in ["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"] {
        assert!(
            boroughs.contains(&borough.to_owned()),
            "no {borough} in {boroughs:?}"
        );
    }
}

#[test]
fn a_zone_join_puts_names_on_the_trips() {
    let playground = loaded();
    let answer = sql(
        &playground,
        "SELECT * FROM trips JOIN zones ON trips.pickup_zone = zones.id \
         WHERE trips.pickup_zone = 132 LIMIT 5",
    );
    assert_eq!(answer["kind"], "join");
    let rows = answer["rows"].as_array().unwrap();
    assert_eq!(rows.len(), 5);
    // Zone 132 is JFK Airport, in Queens. A real fact about a real table; if
    // the join keyed the wrong pair of columns this is what would change.
    for row in rows {
        let cells: Vec<&str> = row
            .as_array()
            .unwrap()
            .iter()
            .map(|c| c.as_str().unwrap())
            .collect();
        assert!(cells.contains(&"JFK Airport"), "{cells:?}");
        assert!(cells.contains(&"Queens"), "{cells:?}");
    }
}

#[test]
fn the_clickhouse_taxi_queries_run() {
    let playground = loaded();

    // ClickHouse's published NYC-taxi benchmark is four queries. Three of them
    // are expressible here; the fourth is not, and saying which is the point
    // of writing them down.
    //
    // Q1 `SELECT cab_type, count(*) ... GROUP BY cab_type` — one vendor here,
    // so `payment` stands in as the low-cardinality key. Same shape.
    let q1 = sql(
        &playground,
        "SELECT payment, count(*) FROM trips GROUP BY payment",
    );
    assert!(q1["rows"].as_array().unwrap().len() >= 2);
    let total: u64 = q1["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|r| r[1].as_str().unwrap().parse::<u64>().unwrap())
        .sum();
    assert_eq!(total, 100_000, "every trip lands in exactly one group");

    // Q2 `SELECT passenger_count, avg(total_amount) ... GROUP BY
    // passenger_count` — verbatim, modulo column names.
    let q2 = sql(
        &playground,
        "SELECT passengers, avg(total) FROM trips GROUP BY passengers",
    );
    assert!(q2["rows"].as_array().unwrap().len() >= 5);

    // Q3 adds the pickup year to the key. There is no date type and no
    // `toYear`, and one month of data has one year in it, so the closest
    // honest thing is a second key that varies: the zone.
    let q3 = sql(
        &playground,
        "SELECT pickup_zone, passengers, count(*) FROM trips GROUP BY pickup_zone, passengers",
    );
    assert!(q3["rows"].as_array().unwrap().len() > 100);

    // Q4 sorts the groups by count descending and takes the top of them. This
    // is the query the whole ordered-grouping path exists for, and the one a
    // reader is most likely to write: *where do most taxis pick up?*
    let q4 = sql(
        &playground,
        "SELECT pickup_zone, count(*) FROM trips GROUP BY pickup_zone \
         ORDER BY count(*) DESC LIMIT 10",
    );
    let rows = q4["rows"].as_array().unwrap();
    assert_eq!(rows.len(), 10, "LIMIT applies to the groups, not the rows");
    let counts: Vec<u64> = rows
        .iter()
        .map(|r| r[1].as_str().unwrap().parse().unwrap())
        .collect();
    assert!(
        counts.windows(2).all(|w| w[0] >= w[1]),
        "groups are not in descending order: {counts:?}"
    );
    // The busiest zone in a real month of yellow-taxi pickups has thousands of
    // trips, not the ~440 an even spread over 226 zones would give. If this
    // ever comes back flat, the ordering is not doing anything.
    assert!(
        counts[0] > 1_000,
        "busiest zone had only {} trips",
        counts[0]
    );
}

#[test]
fn a_filter_on_the_indexed_zone_is_a_real_planner_decision() {
    let playground = loaded();
    // 100,000 rows over 226 zones: a few hundred rows a zone. The index can
    // answer it covering, and cannot pay for itself when rows must be fetched.
    let covering = sql(
        &playground,
        "SELECT pickup_zone FROM trips WHERE pickup_zone = 132",
    );
    assert_eq!(
        covering["plan"]["indexOnly"],
        json!(true),
        "{}",
        covering["plan"]
    );

    let whole = sql(&playground, "SELECT * FROM trips WHERE pickup_zone = 132");
    assert_eq!(whole["plan"]["indexOnly"], json!(false));
    assert_eq!(whole["returned"], covering["returned"]);
}

#[test]
fn every_column_comes_from_the_field_the_format_says_it_does() {
    let bytes = trip_bytes();
    let rows = taxi::decode(&bytes).expect("decode");

    // Unpack the first three records straight from the documented layout in
    // `site/data/make-trips.py` and compare field for field.
    //
    // This exists because a mutation that read the *dropoff* zone into the
    // pickup column changed no test: the join test filters on pickup_zone and
    // joins on pickup_zone, so a consistently wrong column still finds rows
    // and still resolves 132 to JFK. Only an independent reading of the bytes
    // can tell one field from another.
    const BASE: i64 = 1_704_067_200;
    for (i, row) in rows.iter().take(3).enumerate() {
        let r = &bytes[i * 24..(i + 1) * 24];
        let u16_at = |o: usize| u16::from_le_bytes([r[o], r[o + 1]]) as i64;
        let i32_at = |o: usize| i32::from_le_bytes([r[o], r[o + 1], r[o + 2], r[o + 3]]) as i64;
        let v = row.values();

        let number = |value: &slate_tuple::Value| -> i64 {
            match value {
                slate_tuple::Value::U64(n) => *n as i64,
                slate_tuple::Value::I64(n) => *n,
                other => panic!("not a number: {other:?}"),
            }
        };
        let float = |value: &slate_tuple::Value| -> f64 {
            match value {
                slate_tuple::Value::F64(n) => *n,
                other => panic!("not a float: {other:?}"),
            }
        };

        assert_eq!(number(&v[0]), i as i64 + 1, "id");
        assert_eq!(number(&v[1]), u16_at(6), "pickup_zone is bytes 6..8");
        assert_eq!(number(&v[2]), u16_at(8), "dropoff_zone is bytes 8..10");
        assert_eq!(number(&v[3]), BASE + i32_at(0), "pickup_time is bytes 0..4");
        assert_eq!(number(&v[4]), u16_at(4), "duration is bytes 4..6");
        assert!(
            (float(&v[6]) - u16_at(11) as f64 / 100.0).abs() < 1e-9,
            "distance"
        );
        assert!(
            (float(&v[7]) - i32_at(13) as f64 / 100.0).abs() < 1e-9,
            "fare"
        );
        assert!(
            (float(&v[8]) - u16_at(17) as f64 / 100.0).abs() < 1e-9,
            "tip"
        );
        assert!(
            (float(&v[9]) - i32_at(19) as f64 / 100.0).abs() < 1e-9,
            "total"
        );
    }

    // And the two zone columns really do carry different data, so a decoder
    // that read one field into both would not slip past the checks above on a
    // trip that happened to start and end in the same zone.
    let same = rows
        .iter()
        .filter(|r| r.values()[1] == r.values()[2])
        .count();
    assert!(
        same < rows.len() / 2,
        "{same} of {} trips start and end in the same zone; the columns look identical",
        rows.len()
    );
}

// --- aliases --------------------------------------------------------------
//
// The reason aliases exist at all is in this file rather than in `sql.rs`:
// `trips` reaches `zones` twice, through `pickup_zone` and `dropoff_zone`, and
// "the borough it started in and the borough it ended in" is the three-table
// question this dataset is for. Without an alias the second `zones` is a
// refusal, because every column reference resolves against a name and two
// inputs called `zones` make `borough` — and `zones.borough` — ambiguous with
// no way to say which was meant.
//
// So these tests are over the real 100,000 trips, and the checks are
// differentials against queries that ask the same thing another way.

/// `trips` with both ends named: the query aliases exist for.
const BOTH_ENDS: &str = "FROM trips \
                         JOIN zones AS pickup ON trips.pickup_zone = pickup.id \
                         JOIN zones AS dropoff ON trips.dropoff_zone = dropoff.id";

#[test]
fn one_table_twice_names_its_halves_apart() {
    let playground = loaded();
    let answer = sql(&playground, &format!("SELECT * {BOTH_ENDS} LIMIT 5"));
    let columns: Vec<&str> = answer["columns"]
        .as_array()
        .unwrap()
        .iter()
        .map(|c| c.as_str().unwrap())
        .collect();

    // Eleven trip columns, then each `zones` under its own alias. Headed by
    // the table's name, both halves would read `zones.borough` — two columns
    // with one name holding different boroughs, which is a grid that cannot be
    // read.
    assert_eq!(columns.len(), 11 + 4 + 4, "{columns:?}");
    assert_eq!(
        &columns[11..],
        &[
            "pickup.id",
            "pickup.borough",
            "pickup.zone",
            "pickup.service_zone",
            "dropoff.id",
            "dropoff.borough",
            "dropoff.zone",
            "dropoff.service_zone",
        ]
    );

    // And the two halves really are different rows of `zones`, not the same
    // one twice: a chain that joined `pickup` to both steps would pass every
    // check above.
    let rows = answer["rows"].as_array().unwrap();
    assert_eq!(rows.len(), 5);
    for row in rows {
        let row = row.as_array().unwrap();
        assert_eq!(row[11], row[1], "pickup.id is not trips.pickup_zone");
        assert_eq!(row[15], row[2], "dropoff.id is not trips.dropoff_zone");
    }
}

#[test]
fn a_bare_alias_works_and_reads_the_same_rows() {
    // `zones p` as well as `zones AS p`, because both are written. The bare
    // form is the one that can swallow a keyword, so it is worth a test that
    // it did not swallow `ON`.
    let playground = loaded();
    let with_as = sql(
        &playground,
        &format!("SELECT * {BOTH_ENDS} WHERE trips.id = 1072"),
    );
    let bare = sql(
        &playground,
        "SELECT * FROM trips \
         JOIN zones p ON trips.pickup_zone = p.id \
         JOIN zones d ON trips.dropoff_zone = d.id \
         WHERE trips.id = 1072",
    );
    assert_eq!(with_as["rows"], bare["rows"]);
    // Only the headers differ, and they differ by exactly the alias.
    assert_eq!(bare["columns"][12], json!("p.borough"));
    assert_eq!(bare["columns"][16], json!("d.borough"));
}

#[test]
fn grouping_by_one_end_agrees_with_the_two_table_join() {
    let playground = loaded();
    // Every `dropoff_zone` in the data is a real zone id, so the second step
    // drops no rows — checked here rather than assumed, because the whole
    // differential below rests on it.
    let chained = sql(&playground, &format!("SELECT * {BOTH_ENDS}"));
    let all = sql(&playground, "SELECT * FROM trips");
    assert_eq!(
        chained["returned"], all["returned"],
        "the second join dropped trips, so the comparison below is not like for like"
    );

    // With no rows lost, counting by the pickup borough over the chain must
    // equal counting by borough over the plain two-table join. An independent
    // query as the oracle, not a table of numbers.
    let over_chain = sql(
        &playground,
        &format!("SELECT pickup.borough, count(*) {BOTH_ENDS} GROUP BY pickup.borough"),
    );
    let over_join = sql(
        &playground,
        "SELECT borough, count(*) FROM trips JOIN zones ON trips.pickup_zone = zones.id \
         GROUP BY borough",
    );
    assert_eq!(over_chain["rows"], over_join["rows"]);
    assert!(
        over_chain["rows"].as_array().unwrap().len() >= 5,
        "{over_chain}"
    );

    // The header keeps the qualifier here and drops it there, and both are
    // right: `borough` is what the reader wrote over two tables, and names
    // nothing over three where both ends have one.
    assert_eq!(over_chain["columns"][0], json!("pickup.borough"));
    assert_eq!(over_join["columns"][0], json!("borough"));
}

#[test]
fn the_two_ends_are_not_the_same_end() {
    let playground = loaded();
    // The test that would fail if both steps secretly joined the same alias:
    // trips that *change* borough. Counted two ways — once by asking the chain
    // for them, and once by folding the chain's own rows here.
    let changed = sql(
        &playground,
        &format!(
            "SELECT dropoff.borough, count(*) {BOTH_ENDS} \
             WHERE pickup.borough = 'Manhattan' GROUP BY dropoff.borough"
        ),
    );
    let boroughs: Vec<(String, u64)> = changed["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|row| {
            (
                row[0].as_str().unwrap().to_owned(),
                row[1].as_str().unwrap().parse().unwrap(),
            )
        })
        .collect();
    assert!(
        boroughs.len() > 1,
        "every Manhattan pickup ended in one borough, which means the two \
         aliases resolved to the same input: {boroughs:?}"
    );
    let manhattan: u64 = boroughs
        .iter()
        .filter(|(name, _)| name == "Manhattan")
        .map(|(_, n)| *n)
        .sum();
    let total: u64 = boroughs.iter().map(|(_, n)| *n).sum();
    assert!(
        manhattan < total,
        "no Manhattan pickup left Manhattan: {boroughs:?}"
    );
    // And the filter really filtered: fewer than all the trips.
    let all = sql(&playground, "SELECT * FROM trips");
    assert!(total < all["returned"].as_u64().unwrap(), "{total}");
}

#[test]
fn an_alias_is_refused_where_it_cannot_mean_anything() {
    let playground = Playground::new();
    let refused = |text: &str| -> String {
        let all: Vec<Json> = serde_json::from_str(&playground.sql(text)).expect("JSON");
        let last = all.last().expect("a result").clone();
        assert!(!last["error"].is_null(), "{text} was accepted: {last}");
        last["error"]["message"].as_str().unwrap().to_owned()
    };
    // One name twice, which is what an alias is for and so is named as such.
    assert!(
        refused(
            "SELECT * FROM trips JOIN zones ON trips.pickup_zone = zones.id \
             JOIN zones ON trips.dropoff_zone = zones.id"
        )
        .contains("is read twice under one name"),
    );
    // Two aliases that collide, which is the same problem spelled differently.
    assert!(
        refused(
            "SELECT * FROM trips JOIN zones AS z ON trips.pickup_zone = z.id \
             JOIN zones AS z ON trips.dropoff_zone = z.id"
        )
        .contains("is read twice under one name"),
    );
    // A qualifier naming a table the query reads but did not call by that
    // name. `zones` is in the query twice and neither is called `zones`, so
    // this is the error that would otherwise be "not a column of zones" about
    // a column `zones` certainly has.
    assert!(
        refused(&format!(
            "SELECT * {BOTH_ENDS} WHERE zones.borough = 'Queens'"
        ))
        .contains("is qualified with `zones`, which this query does not read"),
    );
    // An alias on a single table, where there is nothing to be told apart.
    assert!(refused("SELECT * FROM books AS b").contains("aliases a single table"),);
    // And the typo that made this rule necessary: a bare word after the first
    // table is an alias only when a JOIN follows it, so a misspelled keyword
    // is still reported as the unexpected word it is.
    assert!(refused("SELECT * FROM books WERE id = 1").contains("unexpected `WERE`"));
}

// --- more than one group key ----------------------------------------------

#[test]
fn a_join_groups_by_two_keys_and_they_fold_back() {
    let playground = loaded();
    // `borough` is column 1 of `zones` and so column 12 of the joined row;
    // `payment` is column 10 of `trips`. Two keys from two different tables,
    // which is the shape a single `Option<u32>` could not hold at all.
    let pairs = sql(
        &playground,
        "SELECT borough, payment, count(*) FROM trips \
         JOIN zones ON trips.pickup_zone = zones.id \
         GROUP BY borough, payment",
    );
    assert_eq!(
        pairs["columns"],
        json!(["borough", "payment", "count(*)"]),
        "{pairs}"
    );

    // The oracle: folding the pairs down to boroughs must give the same counts
    // as grouping by borough alone. An independent query, not a table of
    // numbers -- and it fails if the second key were dropped, doubled, or
    // resolved to the wrong ordinal.
    let mut folded: std::collections::BTreeMap<String, u64> = Default::default();
    for row in pairs["rows"].as_array().unwrap() {
        let row = row.as_array().unwrap();
        *folded
            .entry(row[0].as_str().unwrap().to_owned())
            .or_default() += row[2].as_str().unwrap().parse::<u64>().unwrap();
    }
    let alone = sql(
        &playground,
        "SELECT borough, count(*) FROM trips JOIN zones ON trips.pickup_zone = zones.id \
         GROUP BY borough",
    );
    let expected: std::collections::BTreeMap<String, u64> = alone["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|row| {
            let row = row.as_array().unwrap();
            (
                row[0].as_str().unwrap().to_owned(),
                row[1].as_str().unwrap().parse().unwrap(),
            )
        })
        .collect();
    assert_eq!(folded, expected);
    // And there really were more pairs than boroughs, so this compared
    // something: one payment kind per borough would make the fold trivial.
    assert!(
        pairs["rows"].as_array().unwrap().len() > expected.len(),
        "{} pairs for {} boroughs",
        pairs["rows"].as_array().unwrap().len(),
        expected.len()
    );
}

#[test]
fn ordering_by_an_aggregate_looks_past_every_key() {
    // A group is `[keys..., aggregates...]`, so the first aggregate sits at
    // `keys.len()`. The parser had `i + 1`, which is right for one key and
    // silently off by one for every key after it: `ORDER BY count(*) DESC`
    // over two keys would have ordered by the *second key* instead. Same
    // number of rows, same values, different order, and nothing to report it.
    let playground = loaded();
    let answer = sql(
        &playground,
        "SELECT borough, payment, count(*) FROM trips \
         JOIN zones ON trips.pickup_zone = zones.id \
         GROUP BY borough, payment ORDER BY count(*) DESC",
    );
    let counts: Vec<u64> = answer["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|row| row[2].as_str().unwrap().parse().unwrap())
        .collect();
    assert!(counts.len() > 3, "too few groups to be ordered: {counts:?}");
    assert!(
        counts.windows(2).all(|w| w[0] >= w[1]),
        "not ordered by the count: {counts:?}"
    );
    // The payments are *not* in order, which is what tells this apart from a
    // sort that landed on the second key and happened to look sorted.
    let payments: Vec<&str> = answer["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|row| row[1].as_str().unwrap())
        .collect();
    assert!(
        payments.windows(2).any(|w| w[0] > w[1]),
        "the payments are in order too, so this cannot tell the two apart: {payments:?}"
    );
}

#[test]
fn ordering_by_the_second_key_orders_by_the_second_key() {
    // The other half of the group space: a *key* resolves to its position
    // among the keys, so the second one is 1. Returning 0 -- which is what the
    // one-key version did, because 0 was the only key -- would order by the
    // first key instead. Both are plausible-looking orders over the same rows.
    let playground = loaded();
    let answer = sql(
        &playground,
        "SELECT borough, payment, count(*) FROM trips \
         JOIN zones ON trips.pickup_zone = zones.id \
         GROUP BY borough, payment ORDER BY payment",
    );
    let payments: Vec<&str> = answer["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|row| row[1].as_str().unwrap())
        .collect();
    assert!(payments.len() > 3, "too few groups: {payments:?}");
    assert!(
        payments.windows(2).all(|w| w[0] <= w[1]),
        "not ordered by payment: {payments:?}"
    );
    // And the boroughs are not in order, so an order that landed on the first
    // key would not look like this.
    let boroughs: Vec<&str> = answer["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|row| row[0].as_str().unwrap())
        .collect();
    assert!(
        boroughs.windows(2).any(|w| w[0] > w[1]),
        "the boroughs are in order too, so this cannot tell the two apart: {boroughs:?}"
    );
}

#[test]
fn a_second_key_is_checked_like_the_first() {
    let playground = loaded();
    let refused = |text: &str| -> String {
        let all: Vec<Json> = serde_json::from_str(&playground.sql(text)).expect("JSON");
        let last = all.last().expect("a result").clone();
        assert!(!last["error"].is_null(), "{text} was accepted: {last}");
        last["error"]["message"].as_str().unwrap().to_owned()
    };
    // A selected column that is neither key, with the message now plural.
    assert!(
        refused(
            "SELECT borough, payment, zone, count(*) FROM trips \
             JOIN zones ON trips.pickup_zone = zones.id GROUP BY borough, payment"
        )
        .contains("is not one of the group keys"),
    );
    // And one key still says "the group key", because there is only one.
    assert!(
        refused(
            "SELECT borough, payment, count(*) FROM trips \
             JOIN zones ON trips.pickup_zone = zones.id GROUP BY borough"
        )
        .contains("is not the group key"),
    );
    // A second key that is not a column at all.
    assert!(
        refused(
            "SELECT * FROM trips JOIN zones ON trips.pickup_zone = zones.id \
             GROUP BY borough, nosuch"
        )
        .contains("`nosuch` is not a column of"),
    );
}

// --- HAVING on a join and a chain -----------------------------------------
//
// The single-table path has had HAVING since task #39; the joined path never
// did, because everything downstream of `group_value_type` took one
// `TableDef` and a joined group key is an ordinal of the joined row. The
// kernel needed nothing: `Join::having` and `Chain::having` are `Expr` fields
// it already evaluates over the group.

#[test]
fn having_keeps_exactly_the_groups_that_pass() {
    let playground = loaded();
    let all = sql(
        &playground,
        "SELECT borough, count(*) FROM trips JOIN zones ON trips.pickup_zone = zones.id \
         GROUP BY borough",
    );
    // The oracle is the unfiltered query, filtered here. Not a written-down
    // list of boroughs: a different sample moves both sides together.
    let expected: Vec<&Json> = all["rows"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|row| row[1].as_str().unwrap().parse::<u64>().unwrap() > 5000)
        .collect();
    assert!(
        expected.len() < all["rows"].as_array().unwrap().len(),
        "the threshold filtered nothing, so this compares nothing"
    );
    assert!(!expected.is_empty(), "the threshold filtered everything");

    let filtered = sql(
        &playground,
        "SELECT borough, count(*) FROM trips JOIN zones ON trips.pickup_zone = zones.id \
         GROUP BY borough HAVING count(*) > 5000",
    );
    let got: Vec<&Json> = filtered["rows"].as_array().unwrap().iter().collect();
    assert_eq!(got, expected, "{filtered}");
}

#[test]
fn having_ands_its_terms_over_different_aggregates() {
    let playground = loaded();
    let all = sql(
        &playground,
        "SELECT borough, count(*), avg(total) FROM trips \
         JOIN zones ON trips.pickup_zone = zones.id GROUP BY borough",
    );
    // Thresholds chosen so each term excludes a group the other keeps: EWR has
    // ten trips at a high average, Manhattan has ninety thousand at a low one.
    // The guard below is what forced the choice -- the first pair made the
    // count term do all the work, so the AND was not being tested at all.
    let passes = |row: &Json| {
        row[1].as_str().unwrap().parse::<u64>().unwrap() > 100
            && row[2].as_str().unwrap().parse::<f64>().unwrap() > 30.0
    };
    let expected: Vec<&Json> = all["rows"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|r| passes(r))
        .collect();
    // Both terms have to bite, or an AND that dropped one would pass too.
    let by_count: usize = all["rows"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|r| r[1].as_str().unwrap().parse::<u64>().unwrap() > 100)
        .count();
    let by_avg: usize = all["rows"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|r| r[2].as_str().unwrap().parse::<f64>().unwrap() > 30.0)
        .count();
    assert!(
        expected.len() < by_count && expected.len() < by_avg,
        "one term does all the work: {} of {by_count} by count, {by_avg} by avg",
        expected.len()
    );

    let filtered = sql(
        &playground,
        "SELECT borough, count(*), avg(total) FROM trips \
         JOIN zones ON trips.pickup_zone = zones.id GROUP BY borough \
         HAVING count(*) > 100 AND avg(total) > 30",
    );
    let got: Vec<&Json> = filtered["rows"].as_array().unwrap().iter().collect();
    assert_eq!(got, expected, "{filtered}");
}

#[test]
fn having_works_on_a_chain_and_on_a_group_key() {
    let playground = loaded();
    // Three tables, and the HAVING names the key rather than an aggregate --
    // a group is `[keys..., aggregates...]` and both halves are addressable.
    let filtered = sql(
        &playground,
        "SELECT pickup.borough, count(*) FROM trips \
         JOIN zones AS pickup ON trips.pickup_zone = pickup.id \
         JOIN zones AS dropoff ON trips.dropoff_zone = dropoff.id \
         GROUP BY pickup.borough HAVING count(*) > 1000",
    );
    let boroughs: Vec<&str> = filtered["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|row| row[0].as_str().unwrap())
        .collect();
    assert!(!boroughs.is_empty(), "{filtered}");
    assert!(
        filtered["rows"].as_array().unwrap().iter().all(|row| row[1]
            .as_str()
            .unwrap()
            .parse::<u64>()
            .unwrap()
            > 1000),
        "a group under the threshold survived: {filtered}"
    );
    // And it really dropped some: the same chain without the HAVING has more.
    let all = sql(
        &playground,
        "SELECT pickup.borough, count(*) FROM trips \
         JOIN zones AS pickup ON trips.pickup_zone = pickup.id \
         JOIN zones AS dropoff ON trips.dropoff_zone = dropoff.id \
         GROUP BY pickup.borough",
    );
    assert!(
        boroughs.len() < all["rows"].as_array().unwrap().len(),
        "the HAVING dropped nothing: {boroughs:?}"
    );
}

#[test]
fn having_is_refused_where_it_cannot_mean_anything() {
    let playground = loaded();
    let refused = |text: &str| -> String {
        let all: Vec<Json> = serde_json::from_str(&playground.sql(text)).expect("JSON");
        let last = all.last().expect("a result").clone();
        assert!(!last["error"].is_null(), "{text} was accepted: {last}");
        last["error"]["message"].as_str().unwrap().to_owned()
    };
    // No groups to filter, and the message names the shape the reader is in.
    assert!(
        refused(
            "SELECT * FROM trips JOIN zones ON trips.pickup_zone = zones.id HAVING count(*) > 5"
        )
        .contains("HAVING needs a GROUP BY"),
    );
    // An aggregate the query does not compute. The message says HAVING, not
    // ORDER BY: `join_group_ordinal` serves both clauses and hardcoded the
    // wrong one until it took the clause as a parameter, exactly as the
    // single-table `group_ordinal` already did -- an error naming a clause the
    // reader never wrote sends them to the wrong line.
    let message = refused(
        "SELECT borough, count(*) FROM trips JOIN zones ON trips.pickup_zone = zones.id \
         GROUP BY borough HAVING max(fare) > 5",
    );
    assert!(message.contains("HAVING names `max(fare)`"), "{message}");
    assert!(!message.contains("ORDER BY"), "{message}");
    // OR, refused in HAVING. A single-table WHERE takes it; a HAVING and a
    // join's WHERE do not, and the message says which.
    assert!(
        refused(
            "SELECT borough, count(*) FROM trips JOIN zones ON trips.pickup_zone = zones.id \
             GROUP BY borough HAVING count(*) > 5 OR count(*) < 2"
        )
        .contains("OR is not supported in HAVING"),
    );
}

/// A subquery's null candidates are dropped, and a null outer value is
/// excluded — on the only fixture that has nulls at all.
///
/// The books fixture cannot express this: nothing there is null and the SQL
/// front end has no `NULL` literal, so `IN` over a null candidate is
/// unreachable from a test written against it. Here 4.7% of the month has no
/// passenger count, so `passengers IN (SELECT passengers FROM trips)` is the
/// whole question in one statement: the inner query returns those nulls and
/// the binding drops them, and the outer rows holding a null are excluded
/// because a null equals nothing.
///
/// Both directions collapse to the same count, which is what makes the oracle
/// simple: exactly the rows with a passenger count come back. A build that
/// kept null candidates would still return this number — `Truth::Unknown`
/// excludes as `False` does in a WHERE — so this test cannot tell the two
/// apart, and the assertion on the rendered candidate list below is what does.
///
/// That dropping is also why `NOT IN (SELECT …)` cannot meet a null candidate
/// here: the list it negates has had them removed, so the three-valued case
/// arises only from a literal list, and the front end has no `NULL` literal to
/// write one with. `NOT IN` used to be refused over that case; it is lowered
/// now, and `sql.rs` says why.
#[test]
fn a_subquery_drops_its_null_candidates() {
    let playground = loaded();
    let answer = sql(
        &playground,
        "SELECT count(*) FROM trips WHERE passengers IN (SELECT passengers FROM trips)",
    );

    let rows = taxi::decode(&trip_bytes()).expect("decode");
    let present = rows
        .iter()
        .filter(|r| !matches!(r.values()[5], slate_tuple::Value::Null))
        .count();
    assert!(
        present < rows.len(),
        "no nulls in the fixture, so this proves nothing"
    );

    let got: usize = answer["rows"][0][0]
        .as_str()
        .expect("a count")
        .parse()
        .expect("a number");
    assert_eq!(got, present, "{answer}");

    // And the candidate list itself carries no null: it is rendered to text,
    // and a null that survived would arrive as the string "null" and then fail
    // to parse as a u64 — loudly, but for the wrong reason.
    let values = answer["spec"]["filters"][0]["values"]
        .as_array()
        .expect("values");
    assert!(
        values.iter().all(|v| v.as_str() != Some("null")),
        "a null reached the candidate list"
    );
}
