// Generated by scripts/codegen.py. Do not edit.
//
// A client holds its own copy of the schema and the server checks it:
// every request carries a fingerprint, and a declaration that
// disagrees with the catalog is refused rather than answered
// positionally-wrong. This file is that declaration, produced from the
// catalog itself so the two cannot drift.

import type { Schemas, TableDef } from "@slate-orm/client";

export const AUTHORS: TableDef = {
  name: "authors",
  columns: [
    { name: "id", type: "u64" },
    { name: "name", type: "string" },
    { name: "country", type: "string" },
    { name: "born", type: "i64" },
  ],
  primaryKey: ["id"],
};

export const BOOKS: TableDef = {
  name: "books",
  columns: [
    { name: "id", type: "u64" },
    { name: "author_id", type: "u64" },
    { name: "title", type: "string" },
    { name: "year", type: "i64" },
    { name: "rating", type: "f64" },
    { name: "released", type: "i64" },
    { name: "embedding", type: "vector" },
    { name: "price", type: "decimal", scale: 2 },
  ],
  primaryKey: ["id"],
};

export const SALES: TableDef = {
  name: "sales",
  columns: [
    { name: "id", type: "u64" },
    { name: "book_id", type: "u64" },
    { name: "units", type: "i64" },
  ],
  primaryKey: ["id"],
};

export const EDITIONS: TableDef = {
  name: "editions",
  columns: [
    { name: "id", type: "u64" },
    { name: "book_id", type: "u64" },
    { name: "format", type: "string" },
  ],
  primaryKey: ["id"],
};

/** Every table the catalog declares, for `client.declaring(TABLES)`. */
export const TABLES: Schemas = {
  [AUTHORS.name]: AUTHORS,
  [BOOKS.name]: BOOKS,
  [SALES.name]: SALES,
  [EDITIONS.name]: EDITIONS,
};
