// Generated by scripts/codegen.py. Do not edit.
//
// A client holds its own copy of the schema and the server checks it:
// every request carries a fingerprint, and a declaration that
// disagrees with the catalog is refused rather than answered
// positionally-wrong. This file is that declaration, produced from the
// catalog itself so the two cannot drift.

import type { CheckRule, ForeignKey, Schemas, TableDef, Value } from "@slate-orm/client";

/**
 * One column of a row, with its tag checked.
 *
 * The check is the point. A declaration one column out would otherwise
 * hand back the neighbour, which type-checks at the call site and is
 * wrong; this throws naming the table and the column.
 */
function field(
  row: Value[],
  at: number,
  table: string,
  column: string,
  kind: string,
  nullable: boolean,
): unknown {
  const value = row[at];
  if (value === undefined || value.kind === "null") {
    if (nullable) return null;
    throw new Error(`${table}.${column} is not nullable and came back null`);
  }
  if (value.kind !== kind) {
    throw new Error(
      `${table}.${column} is ${value.kind}, not the declared ${kind}`,
    );
  }
  return "value" in value ? value.value : undefined;
}

export const AUTHORS: TableDef = {
  name: "authors",
  columns: [
    { name: "id", type: "u64" },
    { name: "name", type: "string" },
    { name: "country", type: "string" },
    { name: "born", type: "i64" },
  ],
  primaryKey: ["id"],
};

export const BOOKS: TableDef = {
  name: "books",
  columns: [
    { name: "id", type: "u64" },
    { name: "author_id", type: "u64" },
    { name: "title", type: "string" },
    { name: "year", type: "i64" },
    { name: "rating", type: "f64" },
    { name: "released", type: "i64" },
    { name: "embedding", type: "vector" },
    { name: "price", type: "decimal", scale: 2 },
  ],
  primaryKey: ["id"],
};

export const SALES: TableDef = {
  name: "sales",
  columns: [
    { name: "id", type: "u64" },
    { name: "book_id", type: "u64" },
    { name: "units", type: "i64" },
  ],
  primaryKey: ["id"],
};

export const EDITIONS: TableDef = {
  name: "editions",
  columns: [
    { name: "id", type: "u64" },
    { name: "book_id", type: "u64" },
    { name: "format", type: "string" },
  ],
  primaryKey: ["id"],
};

export const SHIPMENTS: TableDef = {
  name: "shipments",
  columns: [
    { name: "id", type: "u64" },
    { name: "book_id", type: "u64" },
    { name: "status", type: "string" },
    { name: "deleted_at", type: "i64" },
  ],
  primaryKey: ["id"],
};

/** Every table the catalog declares, for `client.declaring(TABLES)`. */
export const TABLES: Schemas = {
  [AUTHORS.name]: AUTHORS,
  [BOOKS.name]: BOOKS,
  [SALES.name]: SALES,
  [EDITIONS.name]: EDITIONS,
  [SHIPMENTS.name]: SHIPMENTS,
};


/** A row of `authors`, decoded. */
export interface Authors {
  id: bigint;
  name: string;
  country: string;
  born: bigint;
}

/**
 * Decode one row of `authors`, by ordinal.
 *
 * Every column's tag is checked rather than assumed. A declaration one
 * column out would otherwise return the neighbour, which type-checks
 * and is wrong; this throws naming the column.
 */
export function decodeAuthors(row: Value[]): Authors {
  if (row.length !== 4) {
    throw new Error(`authors has 4 columns, got ${row.length}`);
  }
  return {
    id: field(row, 0, "authors", "id", "uint", false) as bigint,
    name: field(row, 1, "authors", "name", "string", false) as string,
    country: field(row, 2, "authors", "country", "string", false) as string,
    born: field(row, 3, "authors", "born", "int", false) as bigint,
  };
}

/**
 * Encode one row of `authors` in the catalog column order.
 *
 * `int` and `uint` are both `bigint` on this side, so a hand-built row
 * can carry the wrong tag and still typecheck. This cannot.
 */
export function encodeAuthors(row: Authors): Value[] {
  return [
    { kind: "uint", value: row.id },
    { kind: "string", value: row.name },
    { kind: "string", value: row.country },
    { kind: "int", value: row.born },
  ];
}

/**
 * Every `CHECK` on `books`, by name.
 *
 * Published rather than restated: checks are outside the schema
 * fingerprint, so a client cannot derive them and would otherwise learn
 * each rule from a refusal.
 */
export const BooksChecks: Record<string, CheckRule> = {
  "year_is_positive": { column: "year", message: "Year must be a positive number.", predicate: "year > 0" },
};

/** A row of `books`, decoded. */
export interface Books {
  id: bigint;
  author_id: bigint;
  title: string;
  year: bigint;
  rating: number;
  released: bigint;
  embedding: number[];
  price: bigint;
}

/**
 * Decode one row of `books`, by ordinal.
 *
 * Every column's tag is checked rather than assumed. A declaration one
 * column out would otherwise return the neighbour, which type-checks
 * and is wrong; this throws naming the column.
 */
export function decodeBooks(row: Value[]): Books {
  if (row.length !== 8) {
    throw new Error(`books has 8 columns, got ${row.length}`);
  }
  return {
    id: field(row, 0, "books", "id", "uint", false) as bigint,
    author_id: field(row, 1, "books", "author_id", "uint", false) as bigint,
    title: field(row, 2, "books", "title", "string", false) as string,
    year: field(row, 3, "books", "year", "int", false) as bigint,
    rating: field(row, 4, "books", "rating", "float", false) as number,
    released: field(row, 5, "books", "released", "int", false) as bigint,
    embedding: field(row, 6, "books", "embedding", "vector", false) as number[],
    price: field(row, 7, "books", "price", "units", false) as bigint,
  };
}

/**
 * Encode one row of `books` in the catalog column order.
 *
 * `int` and `uint` are both `bigint` on this side, so a hand-built row
 * can carry the wrong tag and still typecheck. This cannot.
 */
export function encodeBooks(row: Books): Value[] {
  return [
    { kind: "uint", value: row.id },
    { kind: "uint", value: row.author_id },
    { kind: "string", value: row.title },
    { kind: "int", value: row.year },
    { kind: "float", value: row.rating },
    { kind: "int", value: row.released },
    { kind: "vector", value: row.embedding },
    { kind: "units", value: row.price },
  ];
}

/**
 * Every foreign key on `sales`, by name.
 *
 * The parent is the point. A `Relation` names a relationship by the
 * child table and the key, which is all the server needs — but
 * `related` also wants the table its rows decode as, and for a
 * `"parents"` read that is the parent, which no client can derive.
 * The wrong one is refused by the schema check rather than
 * mis-decoded, which was measured; this is a convenience, not a fix.
 */
export const SalesForeignKeys: Record<string, ForeignKey> = {
  "sale_book": { name: "sale_book", child: "sales", parent: "books", onDelete: "restrict" },
};

/** A row of `sales`, decoded. */
export interface Sales {
  id: bigint;
  book_id: bigint;
  units: bigint;
}

/**
 * Decode one row of `sales`, by ordinal.
 *
 * Every column's tag is checked rather than assumed. A declaration one
 * column out would otherwise return the neighbour, which type-checks
 * and is wrong; this throws naming the column.
 */
export function decodeSales(row: Value[]): Sales {
  if (row.length !== 3) {
    throw new Error(`sales has 3 columns, got ${row.length}`);
  }
  return {
    id: field(row, 0, "sales", "id", "uint", false) as bigint,
    book_id: field(row, 1, "sales", "book_id", "uint", false) as bigint,
    units: field(row, 2, "sales", "units", "int", false) as bigint,
  };
}

/**
 * Encode one row of `sales` in the catalog column order.
 *
 * `int` and `uint` are both `bigint` on this side, so a hand-built row
 * can carry the wrong tag and still typecheck. This cannot.
 */
export function encodeSales(row: Sales): Value[] {
  return [
    { kind: "uint", value: row.id },
    { kind: "uint", value: row.book_id },
    { kind: "int", value: row.units },
  ];
}

/**
 * Every foreign key on `editions`, by name.
 *
 * The parent is the point. A `Relation` names a relationship by the
 * child table and the key, which is all the server needs — but
 * `related` also wants the table its rows decode as, and for a
 * `"parents"` read that is the parent, which no client can derive.
 * The wrong one is refused by the schema check rather than
 * mis-decoded, which was measured; this is a convenience, not a fix.
 */
export const EditionsForeignKeys: Record<string, ForeignKey> = {
  "edition_book": { name: "edition_book", child: "editions", parent: "books", onDelete: "restrict" },
};

/** A row of `editions`, decoded. */
export interface Editions {
  id: bigint;
  book_id: bigint;
  format: string;
}

/**
 * Decode one row of `editions`, by ordinal.
 *
 * Every column's tag is checked rather than assumed. A declaration one
 * column out would otherwise return the neighbour, which type-checks
 * and is wrong; this throws naming the column.
 */
export function decodeEditions(row: Value[]): Editions {
  if (row.length !== 3) {
    throw new Error(`editions has 3 columns, got ${row.length}`);
  }
  return {
    id: field(row, 0, "editions", "id", "uint", false) as bigint,
    book_id: field(row, 1, "editions", "book_id", "uint", false) as bigint,
    format: field(row, 2, "editions", "format", "string", false) as string,
  };
}

/**
 * Encode one row of `editions` in the catalog column order.
 *
 * `int` and `uint` are both `bigint` on this side, so a hand-built row
 * can carry the wrong tag and still typecheck. This cannot.
 */
export function encodeEditions(row: Editions): Value[] {
  return [
    { kind: "uint", value: row.id },
    { kind: "uint", value: row.book_id },
    { kind: "string", value: row.format },
  ];
}

/**
 * Every `CHECK` on `shipments`, by name.
 *
 * Published rather than restated: checks are outside the schema
 * fingerprint, so a client cannot derive them and would otherwise learn
 * each rule from a refusal.
 */
export const ShipmentsChecks: Record<string, CheckRule> = {
  "status_known": { column: "status", message: "Status must be pending, shipped or delivered.", predicate: "status in ('pending', 'shipped', 'delivered')" },
  "id_is_seeded": { column: "id", message: "Shipment ids above 9000 are reserved for the demo's own handlers.", predicate: "id < 9000" },
};

/**
 * Every foreign key on `shipments`, by name.
 *
 * The parent is the point. A `Relation` names a relationship by the
 * child table and the key, which is all the server needs — but
 * `related` also wants the table its rows decode as, and for a
 * `"parents"` read that is the parent, which no client can derive.
 * The wrong one is refused by the schema check rather than
 * mis-decoded, which was measured; this is a convenience, not a fix.
 */
export const ShipmentsForeignKeys: Record<string, ForeignKey> = {
  "shipment_book": { name: "shipment_book", child: "shipments", parent: "books", onDelete: "restrict" },
};

/** A row of `shipments`, decoded. */
export interface Shipments {
  id: bigint;
  book_id: bigint;
  status: "pending" | "shipped" | "delivered";
  deleted_at: bigint | null;
}

/**
 * Decode one row of `shipments`, by ordinal.
 *
 * Every column's tag is checked rather than assumed. A declaration one
 * column out would otherwise return the neighbour, which type-checks
 * and is wrong; this throws naming the column.
 */
export function decodeShipments(row: Value[]): Shipments {
  if (row.length !== 4) {
    throw new Error(`shipments has 4 columns, got ${row.length}`);
  }
  return {
    id: field(row, 0, "shipments", "id", "uint", false) as bigint,
    book_id: field(row, 1, "shipments", "book_id", "uint", false) as bigint,
    status: field(row, 2, "shipments", "status", "string", false) as "pending" | "shipped" | "delivered",
    deleted_at: field(row, 3, "shipments", "deleted_at", "int", true) as bigint | null,
  };
}

/**
 * Encode one row of `shipments` in the catalog column order.
 *
 * `int` and `uint` are both `bigint` on this side, so a hand-built row
 * can carry the wrong tag and still typecheck. This cannot.
 */
export function encodeShipments(row: Shipments): Value[] {
  return [
    { kind: "uint", value: row.id },
    { kind: "uint", value: row.book_id },
    { kind: "string", value: row.status },
    row.deleted_at === null ? { kind: "null" } : { kind: "int", value: row.deleted_at },
  ];
}

/**
 * Whether this row of `shipments` has been soft-deleted.
 */
export function isRetiredShipments(row: Shipments): boolean {
  return row.deleted_at !== null;
}
