#!/usr/bin/env python3
"""Every selector `site/style.css` defines is still used by a page or a script.

    python3 scripts/check_site_css.py

`ledger/2026-09-16-the-site-looks-like-the-family-it-belongs-to.md` recorded,
as a caveat, that the stylesheet "still carries rules for elements the
workbench may no longer use". Reading it in the re-triage pass on 2026-09-26
found the answer is **no** — every class and id it names appears somewhere.

The caveat was an admitted unknown rather than a known gap, which is the kind
that stays open for ever: nobody re-derives it, because deriving it is the
whole work. So the derivation is here, and it runs.

# What this catches, and what it does not

A rule for a class nobody writes any more is dead weight in a file a reader
treats as a description of the page. The site has been rewritten twice — the
panel became the workbench, the landing page was restyled — and each time the
markup moved and the stylesheet did not have to.

It does **not** catch the other direction: a class the markup uses and the
stylesheet does not define. That is a styling bug a reader sees immediately,
which is exactly why it does not need a guard; a dead rule is invisible.

Nor does it catch a rule that is *reachable* and pointless — a `.card` that
still exists but whose every property is overridden. That needs a renderer.

# Why substring matching, and why that is not too weak here

A class is "used" if its name occurs anywhere in a page or a script. That
accepts a name mentioned in a comment, and it accepts `"badge " + tone` where
the stylesheet has `.badge[data-tone]`. Both are deliberate: the alternative is
parsing HTML and JavaScript to find every way a class can be attached, which
would refuse the dynamic cases and force a roster of exceptions.

The direction that matters is the one it is strict in. A class that occurs
**nowhere** is unambiguously dead, and that is what it reports. A false *pass*
costs nothing here — the rule stays, as it would have anyway.

`slate_wasm.js` is excluded: it is generated by `wasm-bindgen` and its
megabyte of glue would make almost any three-letter name look used.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

#: Generated, and large enough that any short name matches something in it.
GENERATED = {"slate_wasm.js"}


def sources(site: Path) -> list[Path]:
    """The files a selector may be used by: the pages, and the scripts."""
    found = [p for p in sorted(site.glob("*.html"))]
    found += [p for p in sorted(site.glob("*.js")) if p.name not in GENERATED]
    found += sorted((site / "docs").glob("*.html"))
    return found


def selectors(css: str) -> tuple[set[str], set[str]]:
    """The class and id names the stylesheet defines.

    Comments are stripped first. A `/* .legacy is gone */` note would otherwise
    read as a definition and fail the check against a rule nobody wrote — which
    is the guard reporting on its own input, the failure
    `scripts/check_site_claims.py` met when a code block's numbers looked like
    prose.
    """
    body = re.sub(r"/\*.*?\*/", " ", css, flags=re.DOTALL)
    # A hex colour is not an id. `--line: #ddd` matched `#([a-zA-Z]...)` and
    # produced an "id" named `ddd` that no page could possibly name, so the
    # guard failed every tree including a correct one — found by this file's
    # own first run, on a fixture written to be clean. `#abc`, `#abcd`,
    # `#aabbcc` and `#aabbccdd` are the four CSS hex forms; a longer or
    # shorter run of hex is not a colour and is left to be read as an id.
    body = re.sub(r"#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\b", " ", body)
    classes = set(re.findall(r"\.([a-zA-Z][\w-]*)", body))
    ids = set(re.findall(r"#([a-zA-Z][\w-]*)", body))
    return classes, ids


def check(root: Path) -> list[tuple[str, bool, str]]:
    """`(what, ok, detail)` per check, in the shape the other guards use."""
    out: list[tuple[str, bool, str]] = []

    def record(what: str, ok: bool, detail: str = "") -> None:
        out.append((what, ok, detail))

    site = root / "site"
    stylesheet = site / "style.css"
    if not stylesheet.is_file():
        record("site/style.css exists", False, str(stylesheet))
        return out

    used = "\n".join(p.read_text(encoding="utf-8") for p in sources(site))
    classes, ids = selectors(stylesheet.read_text(encoding="utf-8"))

    record("site/style.css defines some classes", bool(classes), f"{len(classes)}")

    dead = sorted(name for name in classes if name not in used)
    record(
        "every class the stylesheet defines is named by a page or a script",
        not dead,
        ", ".join(dead),
    )

    orphan_ids = sorted(name for name in ids if name not in used)
    record(
        "every id the stylesheet defines is named by a page or a script",
        not orphan_ids,
        ", ".join(orphan_ids),
    )
    return out


def main() -> int:
    failed = 0
    for what, ok, detail in check(REPO):
        if ok:
            print(f"ok    {what}")
        else:
            failed += 1
            print(f"FAIL  {what}" + (f"\n      {detail}" if detail else ""))
    print()
    if failed:
        print(f"{failed} failed")
        return 1
    classes, ids = selectors((REPO / "site" / "style.css").read_text(encoding="utf-8"))
    print(
        f"{len(classes)} classes and {len(ids)} ids in site/style.css, "
        f"all of them reachable from {len(sources(REPO / 'site'))} pages and scripts"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
