#!/usr/bin/env python3
"""Generate a client's schema declaration from the server's own catalog.

# Why this exists

A slate-orm client in another language holds its own copy of the schema. The
protocol publishes none — "the catalog is the server's, and a request names a
table and its columns by the names and ordinals that catalog already has" — so
`Table`/`TableDef` is the client restating it, and the server checks that
restatement with a fingerprint on every request.

That restatement was typed by hand in every client, which is the gap the
comparison against Drizzle and Prisma records: they generate it. Hand-typing it
is not merely tedious, it is the *one* piece of client code where being wrong
is quiet. A wrong ordinal points every reference past it at a different column
and the server cannot tell — the reference is legitimate. The fingerprint
catches it on the first request, which is a good backstop and still a backstop:
the failure has already been written, committed and shipped.

# What it reads

`slate-serverd --config <file> --print-schema`, which resolves the same TOML
the node serves and prints the catalog as JSON. Reading the *resolved* catalog
rather than the TOML is the point: the TOML is a source that the schema layer
interprets — ordinals come from declaration order, a primary key is named and
resolved to ordinals, a decimal's scale is validated — and a generator that
re-interpreted it would be a second implementation of that resolution, free to
disagree with the first. Exactly the disagreement this is meant to end.

# What it writes

One module per target language, each a complete replacement for the file it
overwrites. Generated files carry a header saying so and are checked in,
because a check-in plus `--check` is what makes drift a *CI failure* rather
than something a developer discovers when a request is refused. The
alternative — generating at build time — was rejected for every client here:
Go and TypeScript would need the Rust toolchain present at build time, and the
Python package would need it at install time.

# What it deliberately does not generate

Only the columns, their types and scales, and the primary key — the fields the
fingerprint hashes, which is exactly the set where being wrong is silent. Not
indexes: a client never names one on the wire (`Hint` takes a name, and a wrong
name is an error the server reports). Not `added_in`/`dropped_in`: a client
that pins a schema version is a client that stops working on the next
migration. Generating the fingerprint itself was considered and rejected — the
whole value of the check is that the client computes it from the declaration it
actually holds, so a generated constant would make the check tautological.

Usage:

    python3 scripts/codegen.py --config examples/explorer/head.toml \\
        --python examples/explorer/backends/python/adapter/schema.py
    python3 scripts/codegen.py --config examples/explorer/head.toml \\
        --python <path> --check
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: A catalog type name, as `--print-schema` spells it, mapped onto what each
#: client calls it.
#:
#: Three separate tables rather than one with three columns, because the sets
#: are not guaranteed to stay in step: a type this generator does not know
#: about is a hard error below, and it should be possible to add one to a
#: single client without inventing spellings for the other two.
PYTHON_TYPES = {
    "bool": "ValueType.BOOL",
    "bytes": "ValueType.BYTES",
    "string": "ValueType.STR",
    "i64": "ValueType.I64",
    "u64": "ValueType.U64",
    "f64": "ValueType.F64",
    "uuid": "ValueType.UUID",
    "vector": "ValueType.VECTOR",
    "decimal": "ValueType.DECIMAL",
}

GO_TYPES = {
    "bool": "slate.TypeBool",
    "bytes": "slate.TypeBytes",
    "string": "slate.TypeString",
    "i64": "slate.TypeInt",
    "u64": "slate.TypeUint",
    "f64": "slate.TypeFloat",
    "uuid": "slate.TypeUUID",
    "vector": "slate.TypeVector",
    "decimal": "slate.TypeDecimal",
}

TYPESCRIPT_TYPES = {
    "bool": '"bool"',
    "bytes": '"bytes"',
    "string": '"string"',
    "i64": '"i64"',
    "u64": '"u64"',
    "f64": '"f64"',
    "uuid": '"uuid"',
    "vector": '"vector"',
    "decimal": '"decimal"',
}

BANNER = "Generated by scripts/codegen.py. Do not edit."


class Unknown(Exception):
    """A catalog type no target language has a spelling for.

    Raised rather than passed through or guessed at. A generator that emitted
    an unknown type as a string would produce a file that fails to compile,
    which is survivable; one that guessed would produce a declaration that
    compiles and hashes to the wrong fingerprint, which is the failure this
    whole tool exists to prevent.
    """


def catalog(config: Path, serverd: str) -> dict:
    """The resolved catalog, as the node would serve it."""
    printed = subprocess.run(
        [serverd, "--config", str(config), "--print-schema"],
        capture_output=True,
        text=True,
        check=False,
    )
    if printed.returncode != 0:
        raise SystemExit(
            f"`{serverd} --config {config} --print-schema` failed "
            f"({printed.returncode}):\n{printed.stderr}"
        )
    return json.loads(printed.stdout)


def live_columns(table: dict) -> list[dict]:
    """The columns a client declares: every one, in ordinal order.

    Dropped columns are *kept*. A dropped column holds its ordinal — that is
    the whole design of the schema layer's `dropped_in`, so that a column
    removed from the middle does not re-point everything after it — and a
    declaration that skipped it would shift every later ordinal by one and
    silently read the wrong column, which is the exact failure being generated
    away from. The ordinals are asserted contiguous rather than trusted.
    """
    columns = sorted(table["columns"], key=lambda column: column["ordinal"])
    for at, column in enumerate(columns):
        if column["ordinal"] != at:
            raise SystemExit(
                f"table `{table['name']}` has a gap at ordinal {at}: "
                f"`{column['name']}` claims {column['ordinal']}. "
                "A declaration built from this would be wrong."
            )
    return columns


def key_names(table: dict, columns: list[dict]) -> list[str]:
    """The primary key, as names rather than the ordinals the catalog holds.

    Every client's declaration names its key columns, because a key given as
    ordinals would be a second place to get an ordinal wrong.
    """
    return [columns[ordinal]["name"] for ordinal in table["primary_key"]]


def spelling(table: dict, types: dict[str, str]) -> str:
    """A table's constant name: the table name, upper-cased.

    `books` becomes `BOOKS`. Collisions are impossible because a catalog cannot
    hold two tables with the same name, and case-folding cannot merge two
    distinct names that differ only in case — the schema layer refuses those
    too.
    """
    del types
    return table["name"].upper().replace("-", "_")


def python_module(tables: list[dict]) -> str:
    """The Python client's declaration."""
    out = [
        '"""The server\'s tables, as this client must declare them.',
        "",
        f"{BANNER}",
        "",
        "A client holds its own copy of the schema and the server checks it:",
        "every request carries a fingerprint, and a declaration that disagrees",
        "with the catalog is refused rather than answered positionally-wrong.",
        "This file is that declaration, produced from the catalog itself so the",
        "two cannot drift.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from slate import Column, Table, ValueType",
        "",
        "__all__ = [",
    ]
    names = [spelling(table, PYTHON_TYPES) for table in tables]
    out.extend(f'    "{name}",' for name in sorted([*names, "BY_NAME"]))
    out.extend(["]", ""])

    for table in tables:
        columns = live_columns(table)
        out.append(f"{spelling(table, PYTHON_TYPES)} = Table(")
        out.append(f'    "{table["name"]}",')
        out.append("    [")
        for column in columns:
            kind = PYTHON_TYPES.get(column["type"])
            if kind is None:
                raise Unknown(f"python has no spelling for `{column['type']}`")
            scale = "" if column["scale"] is None else f", scale={column['scale']}"
            out.append(f'        Column("{column["name"]}", {kind}{scale}),')
        out.append("    ],")
        key = ", ".join(f'"{name}"' for name in key_names(table, columns))
        out.append(f"    primary_key=[{key}],")
        out.extend([")", ""])

    joined = ", ".join(names)
    out.append(f"BY_NAME = {{table.name: table for table in ({joined},)}}")
    out.append("")
    return "\n".join(out)


def go_file(tables: list[dict], package: str) -> str:
    """The Go client's declaration."""
    out = [
        f"// {BANNER}",
        "",
        "// A client holds its own copy of the schema and the server checks it:",
        "// every request carries a fingerprint, and a declaration that",
        "// disagrees with the catalog is refused rather than answered",
        "// positionally-wrong. This file is that declaration, produced from the",
        "// catalog itself so the two cannot drift.",
        f"package {package}",
        "",
        'import "github.com/howlerops/slate-orm/clients/go/slate"',
        "",
        "// Tables is every table the catalog declares, ready for",
        "// `client.Declaring(schema.Tables)`.",
        "var Tables = slate.Schemas{",
    ]
    for table in tables:
        columns = live_columns(table)
        out.append(f'\t"{table["name"]}": {{')
        out.append(f'\t\tName: "{table["name"]}",')
        out.append("\t\tColumns: []slate.ColumnDef{")
        for column in columns:
            kind = GO_TYPES.get(column["type"])
            if kind is None:
                raise Unknown(f"go has no spelling for `{column['type']}`")
            scale = "" if column["scale"] is None else f", Scale: {column['scale']}"
            out.append(f'\t\t\t{{Name: "{column["name"]}", Type: {kind}{scale}}},')
        out.append("\t\t},")
        key = ", ".join(f'"{name}"' for name in key_names(table, columns))
        out.append(f"\t\tPrimaryKey: []string{{{key}}},")
        out.append("\t},")
    out.extend(["}", ""])
    return "\n".join(out)


def typescript_module(tables: list[dict]) -> str:
    """The TypeScript client's declaration."""
    out = [
        "// " + BANNER,
        "//",
        "// A client holds its own copy of the schema and the server checks it:",
        "// every request carries a fingerprint, and a declaration that",
        "// disagrees with the catalog is refused rather than answered",
        "// positionally-wrong. This file is that declaration, produced from the",
        "// catalog itself so the two cannot drift.",
        "",
        'import type { Schemas, TableDef } from "@slate-orm/client";',
        "",
    ]
    names = []
    for table in tables:
        columns = live_columns(table)
        name = spelling(table, TYPESCRIPT_TYPES)
        names.append(name)
        out.append(f"export const {name}: TableDef = {{")
        out.append(f'  name: "{table["name"]}",')
        out.append("  columns: [")
        for column in columns:
            kind = TYPESCRIPT_TYPES.get(column["type"])
            if kind is None:
                raise Unknown(f"typescript has no spelling for `{column['type']}`")
            scale = "" if column["scale"] is None else f", scale: {column['scale']}"
            out.append(f'    {{ name: "{column["name"]}", type: {kind}{scale} }},')
        out.append("  ],")
        key = ", ".join(f'"{name}"' for name in key_names(table, columns))
        out.append(f"  primaryKey: [{key}],")
        out.extend(["};", ""])

    out.append("/** Every table the catalog declares, for `client.declaring(TABLES)`. */")
    out.append("export const TABLES: Schemas = {")
    out.extend(f"  [{name}.name]: {name}," for name in names)
    out.extend(["};", ""])
    return "\n".join(out)


def emit(path: Path, body: str, check: bool) -> bool:
    """Write `body` to `path`, or compare and report. True means agreement."""
    if check:
        if not path.exists():
            print(f"miss  {path} does not exist", file=sys.stderr)
            return False
        if path.read_text(encoding="utf-8") != body:
            print(f"drift {path} is not what the catalog says", file=sys.stderr)
            return False
        print(f"ok    {path}")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    print(f"wrote {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--python", type=Path)
    parser.add_argument("--go", type=Path)
    parser.add_argument("--go-package", default="schema")
    parser.add_argument("--typescript", type=Path)
    parser.add_argument(
        "--serverd",
        # The same variable the client harnesses use, so a run with a prebuilt
        # binary needs no second thing to set. A path that is set and missing is
        # a hard error in `catalog`, never a silent fall back to building.
        default=os.environ.get("SLATE_SERVERD", "target/debug/slate-serverd"),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare instead of writing; non-zero if anything has drifted",
    )
    arguments = parser.parse_args()

    if not (arguments.python or arguments.go or arguments.typescript):
        parser.error("name at least one of --python, --go, --typescript")

    tables = catalog(arguments.config, arguments.serverd)["tables"]
    agreed = True
    if arguments.python:
        agreed &= emit(arguments.python, python_module(tables), arguments.check)
    if arguments.go:
        body = go_file(tables, arguments.go_package)
        agreed &= emit(arguments.go, body, arguments.check)
    if arguments.typescript:
        agreed &= emit(arguments.typescript, typescript_module(tables), arguments.check)

    if not agreed:
        print(
            "\nthe checked-in declarations disagree with the catalog; "
            "re-run without --check",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
