#!/usr/bin/env python3
"""Write `container/head.toml` from `examples/explorer/head.toml`.

Derived rather than copied, so the deployed node serves exactly the tables,
grants, policies and views the conformance runner exercises. Three sections
change, and each change is refused if the source no longer has the shape it
expects, rather than producing a config that quietly differs:

- `[listen]` binds every interface on 7421, because inside a container the
  Worker connects from outside the loopback;
- `[auth]` is `token`, reading each persona's secret from `SLATE_TOKEN_<NAME>`,
  with `transport = "tls-terminated-upstream"`: the Worker terminates TLS and
  the hop to the container is Cloudflare's internal container network;
- `[storage]` is S3 with `from_env = true`, so R2's bucket, endpoint and keys
  come from `SLATE_S3_*` and nothing account-specific is in the image.

It also appends two read replicas and a `[routing]` budget, which the source
does not have: the explorer's own node runs in memory, where a replica has
nothing to read. See `REPLICAS`.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent.parent / "explorer" / "head.toml"
TARGET = HERE / "head.toml"

#: The explorer's personas, with the identities its adapters use for them.
PERSONAS = {
    "app": "u64:1",
    "reader": "u64:2",
    "stranger": "u64:3",
    "analyst": "u64:4",
}


#: Two read replicas in each node, and how far behind they may be.
#:
#: Two so that `/api/served-by` can name different ones on successive reads;
#: one would look the same as the writer serving every read.
#:
#: `catch_up` is set because its default, 250 ms, makes each replica poll the
#: manifest every 50 ms (`storage::poll_interval` takes a fifth), and on R2
#: every poll is a billed read: two nodes with two replicas each would make
#: about 80 a second while awake. Five seconds polls once a second. The cost
#: is that a read carrying a fresh sequence may wait up to about a second for
#: a replica, or is served by the writer.
REPLICAS = """
[[replicas]]
name = "reader-1"

[[replicas]]
name = "reader-2"

[routing]
catch_up = "5s"
"""


def main() -> int:
    text = SOURCE.read_text()
    replacements = {
        'address = "127.0.0.1:7421"': 'address = "0.0.0.0:7421"',
        '[auth]\nmode = "trusted-header"\n': '[auth]\nmode = "token"\ntransport = "tls-terminated-upstream"\n\n'
        + "".join(
            f'[[auth.tokens]]\nname = "{name}"\nsecret_env = "SLATE_TOKEN_{name.upper()}"\n'
            f'principal = "{principal}"\ntenant = "u64:1"\nroles = ["{name}"]\n\n'
            for name, principal in PERSONAS.items()
        ),
        '[storage]\nbackend = "memory"\n': '[storage]\nbackend = "s3"\npath = "explorer"\n\n[storage.s3]\nfrom_env = true\n',
    }
    for old, new in replacements.items():
        if text.count(old) != 1:
            print(
                f"examples/explorer/head.toml no longer contains {old!r} exactly once",
                file=sys.stderr,
            )
            return 1
        text = text.replace(old, new)
    for header in ("[[replicas]]", "[routing]"):
        if header in text:
            print(f"examples/explorer/head.toml now has {header}; merge it here", file=sys.stderr)
            return 1
    TARGET.write_text(
        "# Generated by examples/edge/container/derive.py from examples/explorer/head.toml.\n"
        + text
        + REPLICAS
    )
    print(f"wrote {TARGET.relative_to(HERE.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
