// Generated by scripts/codegen.py. Do not edit.
//
// Names only: no import, no `TableDef`, nothing from the SDK. A browser
// app uses this to label columns, and the SDK is a gRPC client.
//
// Every column the catalog carries, in ordinal order, dropped ones
// included — a dropped column keeps its slot in the row, so leaving it
// out would shift every later header onto the wrong value.

/** Every table the catalog declares, as name -> column names in ordinal order. */
export const CATALOG_TABLES: Record<string, string[]> = {
  authors: ["id", "name", "country", "born"],
  books: ["id", "author_id", "title", "year", "rating", "released", "embedding", "price"],
  sales: ["id", "book_id", "units"],
  editions: ["id", "book_id", "format"],
  posts: ["id", "title", "tags", "sizes"],
  shipments: ["id", "book_id", "status", "deleted_at"],
};

/** Every view, as name -> its base table's column names.
 *
 * The same array object as the base table's, not a copy: a view may not
 * narrow columns, so its ordinals *are* the table's and a second list is
 * a second thing to get wrong.
 */
export const CATALOG_VIEWS: Record<string, string[]> = {
  classics: CATALOG_TABLES["books"]!,
};
