// Generated by scripts/codegen.py. Do not edit.

// A client holds its own copy of the schema and the server checks it:
// every request carries a fingerprint, and a declaration that
// disagrees with the catalog is refused rather than answered
// positionally-wrong. This file is that declaration, produced from the
// catalog itself so the two cannot drift.
package schema

import "github.com/howlerops/slate-orm/clients/go/slate"

// Tables is every table the catalog declares, ready for
// `client.Declaring(schema.Tables)`.
var Tables = slate.Schemas{
	"authors": {
		Name: "authors",
		Columns: []slate.ColumnDef{
			{Name: "id", Type: slate.TypeUint},
			{Name: "name", Type: slate.TypeString},
			{Name: "country", Type: slate.TypeString},
			{Name: "born", Type: slate.TypeInt},
		},
		PrimaryKey: []string{"id"},
	},
	"books": {
		Name: "books",
		Columns: []slate.ColumnDef{
			{Name: "id", Type: slate.TypeUint},
			{Name: "author_id", Type: slate.TypeUint},
			{Name: "title", Type: slate.TypeString},
			{Name: "year", Type: slate.TypeInt},
			{Name: "rating", Type: slate.TypeFloat},
			{Name: "released", Type: slate.TypeInt},
			{Name: "embedding", Type: slate.TypeVector},
			{Name: "price", Type: slate.TypeDecimal, Scale: 2},
		},
		PrimaryKey: []string{"id"},
	},
	"sales": {
		Name: "sales",
		Columns: []slate.ColumnDef{
			{Name: "id", Type: slate.TypeUint},
			{Name: "book_id", Type: slate.TypeUint},
			{Name: "units", Type: slate.TypeInt},
		},
		PrimaryKey: []string{"id"},
	},
	"editions": {
		Name: "editions",
		Columns: []slate.ColumnDef{
			{Name: "id", Type: slate.TypeUint},
			{Name: "book_id", Type: slate.TypeUint},
			{Name: "format", Type: slate.TypeString},
		},
		PrimaryKey: []string{"id"},
	},
}
